#!/usr/bin/env bash
set -euo pipefail

usage() { echo "usage: $0 ARTIFACT_DIR config|up|ps|logs|down" >&2; exit 2; }
test "$#" -ge 2 || usage
artifact_dir=$1
action=$2
shift 2
case "$artifact_dir" in /*) ;; *) usage ;; esac
case "$action" in config|up|ps|logs|down) ;; *) usage ;; esac
unset COMPOSE_PROFILES
deploy_dir=$(cd "$(dirname "$0")" && pwd -P)
repo_dir=$(cd "$deploy_dir/../.." && pwd -P)
lock="$artifact_dir/.runtime-lock.env"
test -r "$lock" || { echo 'artifact lock is missing' >&2; exit 1; }
# The lock is generated by build-artifacts.sh. Parse fixed keys as literal
# values; a root invocation must never execute an operator-owned env file.
test ! -L "$lock" || { echo 'artifact lock cannot be a symlink' >&2; exit 1; }
mode=$(stat -c %a "$lock")
case "$mode" in 600|400) ;; *) echo 'artifact lock must have mode 600 or 400' >&2; exit 1 ;; esac
unset CATHEDRAL_RUNTIME_GIT_REVISION CATHEDRAL_ARTIFACT_DIR CATHEDRAL_DEPLOY_DIR \
  CATHEDRAL_API_IMAGE CATHEDRAL_API_IMAGE_ID CATHEDRAL_DB_MIGRATOR_IMAGE \
  CATHEDRAL_DB_MIGRATOR_IMAGE_ID
seen=':'
while IFS= read -r line || test -n "$line"; do
  key=${line%%=*}
  value=${line#*=}
  test "$key" != "$line" && test -n "$value" || { echo 'invalid artifact lock line' >&2; exit 1; }
  case "$seen" in *":$key:"*) echo "duplicate artifact lock key $key" >&2; exit 1 ;; esac
  seen="$seen$key:"
  case "$key" in
    CATHEDRAL_RUNTIME_GIT_REVISION) CATHEDRAL_RUNTIME_GIT_REVISION=$value ;;
    CATHEDRAL_ARTIFACT_DIR) CATHEDRAL_ARTIFACT_DIR=$value ;;
    CATHEDRAL_DEPLOY_DIR) CATHEDRAL_DEPLOY_DIR=$value ;;
    CATHEDRAL_API_IMAGE) CATHEDRAL_API_IMAGE=$value ;;
    CATHEDRAL_API_IMAGE_ID) CATHEDRAL_API_IMAGE_ID=$value ;;
    CATHEDRAL_DB_MIGRATOR_IMAGE) CATHEDRAL_DB_MIGRATOR_IMAGE=$value ;;
    CATHEDRAL_DB_MIGRATOR_IMAGE_ID) CATHEDRAL_DB_MIGRATOR_IMAGE_ID=$value ;;
    *) echo "unknown artifact lock key $key" >&2; exit 1 ;;
  esac
done < "$lock"
for key in CATHEDRAL_RUNTIME_GIT_REVISION CATHEDRAL_ARTIFACT_DIR CATHEDRAL_DEPLOY_DIR \
  CATHEDRAL_API_IMAGE CATHEDRAL_API_IMAGE_ID CATHEDRAL_DB_MIGRATOR_IMAGE \
  CATHEDRAL_DB_MIGRATOR_IMAGE_ID; do
  test -n "${!key:-}" || { echo "missing artifact lock key $key" >&2; exit 1; }
done
export CATHEDRAL_RUNTIME_GIT_REVISION CATHEDRAL_ARTIFACT_DIR CATHEDRAL_DEPLOY_DIR \
  CATHEDRAL_API_IMAGE CATHEDRAL_API_IMAGE_ID CATHEDRAL_DB_MIGRATOR_IMAGE \
  CATHEDRAL_DB_MIGRATOR_IMAGE_ID
test "$CATHEDRAL_RUNTIME_GIT_REVISION" = f11618e72af6996d4df3290078a6d54fd3099649
test "$CATHEDRAL_ARTIFACT_DIR" = "$artifact_dir"
test "$CATHEDRAL_DEPLOY_DIR" = "$deploy_dir"
test "$(sha256sum "$artifact_dir/orchestrator" | cut -d ' ' -f 1)" = \
  "$(cut -d ' ' -f 1 < "$artifact_dir/orchestrator.sha256")" || {
  echo 'Cathedral orchestrator checksum mismatch' >&2; exit 1;
}
test "$(docker image inspect --format '{{.Id}}' "$CATHEDRAL_API_IMAGE")" = "$CATHEDRAL_API_IMAGE_ID" || {
  echo 'Cathedral API image ID changed' >&2; exit 1;
}
test "$(docker image inspect --format '{{.Id}}' "$CATHEDRAL_DB_MIGRATOR_IMAGE")" = "$CATHEDRAL_DB_MIGRATOR_IMAGE_ID" || {
  echo 'Cathedral migrator image ID changed' >&2; exit 1;
}
compose=(docker compose -p cathedral-proof
  --env-file "$repo_dir/embed/compose/.env"
  --env-file "$lock"
  -f "$repo_dir/embed/compose/compose.yaml"
  -f "$deploy_dir/compose.proof.yaml")
case "$action" in
  up)
    test "$(id -u)" -eq 0 || { echo 'run proof-host up as root to verify the nft ingress guard' >&2; exit 1; }
    "$deploy_dir/ingress-guard.sh" check
    "${compose[@]}" config --quiet
    exec "${compose[@]}" up -d --wait "$@"
    ;;
  config) exec "${compose[@]}" config "$@" ;;
  ps) exec "${compose[@]}" ps "$@" ;;
  logs) exec "${compose[@]}" logs "$@" ;;
  down) exec "${compose[@]}" down "$@" ;;
esac
