// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lock_public_user_for_update.sql

package authqueries

import (
	"context"

	"github.com/google/uuid"
)

const lockPublicUserForUpdate = `-- name: LockPublicUserForUpdate :one
SELECT id
FROM public.users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockPublicUserForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPublicUserForUpdate, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}
