// Package envd provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package envd

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EntryInfoType.
const (
	File EntryInfoType = "file"
)

// Valid indicates whether the value is a known member of the EntryInfoType enum.
func (e EntryInfoType) Valid() bool {
	switch e {
	case File:
		return true
	default:
		return false
	}
}

// Defines values for FreezeResultMode.
const (
	FreezeResultModeHierarchy FreezeResultMode = "hierarchy"
	FreezeResultModeLegacy    FreezeResultMode = "legacy"
)

// Valid indicates whether the value is a known member of the FreezeResultMode enum.
func (e FreezeResultMode) Valid() bool {
	switch e {
	case FreezeResultModeHierarchy:
		return true
	case FreezeResultModeLegacy:
		return true
	default:
		return false
	}
}

// Defines values for PostFreezeParamsMode.
const (
	PostFreezeParamsModeHierarchy PostFreezeParamsMode = "hierarchy"
	PostFreezeParamsModeLegacy    PostFreezeParamsMode = "legacy"
)

// Valid indicates whether the value is a known member of the PostFreezeParamsMode enum.
func (e PostFreezeParamsMode) Valid() bool {
	switch e {
	case PostFreezeParamsModeHierarchy:
		return true
	case PostFreezeParamsModeLegacy:
		return true
	default:
		return false
	}
}

// Defines values for PostInitJSONBodyThaw.
const (
	Inline PostInitJSONBodyThaw = "inline"
	Skip   PostInitJSONBodyThaw = "skip"
)

// Valid indicates whether the value is a known member of the PostInitJSONBodyThaw enum.
func (e PostInitJSONBodyThaw) Valid() bool {
	switch e {
	case Inline:
		return true
	case Skip:
		return true
	default:
		return false
	}
}

// CollapseResult Per-call statistics from a heap collapse
type CollapseResult struct {
	// AlreadyHuge Chunks MADV_COLLAPSE accepted but were already hugepages (no work)
	AlreadyHuge int `json:"alreadyHuge,omitempty"`

	// Chunks 2 MiB chunks attempted
	Chunks int `json:"chunks,omitempty"`

	// Collapsed Chunks whose base pages were actually migrated into a new hugepage (real work)
	Collapsed int `json:"collapsed,omitempty"`

	// ElapsedMs Wall-clock time spent collapsing, in milliseconds
	ElapsedMs int64 `json:"elapsedMs,omitempty"`

	// Regions Anonymous read-write regions scanned
	Regions int `json:"regions,omitempty"`

	// Skipped Chunks that could not be collapsed (empty or ineligible)
	Skipped int `json:"skipped,omitempty"`
}

// ComposeRequest defines model for ComposeRequest.
type ComposeRequest struct {
	// Destination Destination file path for the composed file
	Destination string `json:"destination"`

	// SourcePaths Ordered list of source file paths to concatenate
	SourcePaths []string `json:"source_paths"`

	// Username User for setting ownership and resolving relative paths
	Username string `json:"username,omitempty"`
}

// EntryInfo defines model for EntryInfo.
type EntryInfo struct {
	// Metadata User-defined metadata stored as extended attributes on the file.
	Metadata map[string]string `json:"metadata,omitempty"`

	// Name Name of the file
	Name string `json:"name"`

	// Path Path to the file
	Path string `json:"path"`

	// Type Type of the file
	Type EntryInfoType `json:"type"`
}

// EntryInfoType Type of the file
type EntryInfoType string

// EnvVars Environment variables to set
type EnvVars map[string]string

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// FreezeResult Per-call statistics from a pre-pause workload freeze
type FreezeResult struct {
	// Allowlisted Cgroups skipped because the resume path depends on them (systemd, journald, envd's port forwarding). Reported because the allowlist is expected to grow, and a distro that routes journald differently changes this count
	Allowlisted int `json:"allowlisted,omitempty"`

	// Failed Cgroups that errored for a reason that is not simply being gone - the write was refused, or the state could not be read. A cgroup the hierarchy walk discovered that merely went away is counted vanished instead; one of envd's own static cgroups that goes away is counted here, by design
	Failed int `json:"failed,omitempty"`

	// Frozen Cgroups that read back "frozen 1" from cgroup.events within the budget; their tasks have stopped
	Frozen int `json:"frozen,omitempty"`

	// Mode Which sweep actually ran. Echoed back rather than inferred from the flag, so a caller can tell that envd honoured what it asked for
	Mode FreezeResultMode `json:"mode,omitempty"`

	// NotFrozen Cgroups still reading "frozen 0" when the budget expired; their tasks may still be running, so a snapshot taken now can capture a live workload
	NotFrozen int `json:"notFrozen,omitempty"`

	// PreFrozen Cgroups the guest itself had already frozen before the sweep ran (docker pause writes cgroup.freeze). Not written to and deliberately left frozen by the resume thaw, so the guest's own suspension survives the snapshot
	PreFrozen int `json:"preFrozen,omitempty"`

	// Requested Cgroups this call wrote cgroup.freeze to
	Requested int `json:"requested,omitempty"`

	// SweepMs Time spent issuing the freeze writes, in milliseconds (scales with cgroup count)
	SweepMs int64 `json:"sweepMs,omitempty"`

	// Truncated True when the walk stopped because it hit the bound rather than because it ran out of tree, so coverage is incomplete
	Truncated bool `json:"truncated,omitempty"`

	// Unobservable Cgroups whose freeze state cannot be read because this guest has no cgroup manager; the write was accepted but nothing can be read back, so these are neither frozen nor notFrozen
	Unobservable int `json:"unobservable,omitempty"`

	// Vanished Cgroups the hierarchy walk enumerated that the guest then removed before the sweep finished with them - envd's own static cgroups are excluded and report failed instead. A race rather than a failure, and a claim about the cgroup only - tasks migrated out of it before its removal can still be running. Like failed it spans both phases, so it does not reconcile against requested on its own - one removed during the settle poll was counted in requested, one removed before its write never was
	Vanished int `json:"vanished,omitempty"`

	// Visited Cgroups the walk examined, whether or not it froze them. The input for sizing the bound; meaningless in legacy mode
	Visited int `json:"visited,omitempty"`

	// WaitMs Time spent polling cgroup.events, in milliseconds (scales with how deep in I/O the guest tasks were). Outcome neutral - the wait ends either because everything stopped or because the budget ran out
	WaitMs int64 `json:"waitMs,omitempty"`
}

// FreezeResultMode Which sweep actually ran. Echoed back rather than inferred from the flag, so a caller can tell that envd honoured what it asked for
type FreezeResultMode string

// Metrics Resource usage metrics
type Metrics struct {
	// CpuCount Number of CPU cores online
	CpuCount int `json:"cpu_count,omitempty"`

	// CpuPossible Number of CPUs the guest can bring online
	CpuPossible int `json:"cpu_possible,omitempty"`

	// CpuTarget Online count last requested, 0 when none was
	CpuTarget int `json:"cpu_target,omitempty"`

	// CpuTargetAttempts Attempts at reaching cpu_target since it was set
	CpuTargetAttempts int `json:"cpu_target_attempts,omitempty"`

	// CpuUsedPct CPU usage percentage
	CpuUsedPct float32 `json:"cpu_used_pct,omitempty"`

	// CpuWritePendingMs How long a CPU online or offline write has been running in the guest kernel, 0 when none is. A value that keeps growing means CPU hotplug is stuck.
	CpuWritePendingMs int64 `json:"cpu_write_pending_ms,omitempty"`

	// DiskTotal Total disk space in bytes
	DiskTotal int `json:"disk_total,omitempty"`

	// DiskUsed Used disk space in bytes
	DiskUsed int `json:"disk_used,omitempty"`

	// MemCache Cached memory (page cache) in bytes
	MemCache int `json:"mem_cache,omitempty"`

	// MemTotal Total virtual memory in bytes
	MemTotal int `json:"mem_total,omitempty"`

	// MemUsed Used virtual memory in bytes
	MemUsed int `json:"mem_used,omitempty"`

	// OomKills The latest 32 out-of-memory kills since the guest booted, oldest first. Reading does not consume them. Empty when there are none. Omitted when not known (while envd is still reading the kernel log, when it can't be read or envd stopped reading it, and outside Firecracker).
	OomKills *[]OOMKill `json:"oom_kills,omitempty"`

	// Ts Unix timestamp in UTC for current sandbox time
	Ts int64 `json:"ts,omitempty"`
}

// OOMKill A process the guest kernel killed for running out of memory
type OOMKill struct {
	// Process Name of the killed process, or Unknown if the record doesn't show it
	Process string `json:"process"`

	// Seq Kernel log sequence number of the kill record. It only grows, across pauses and envd restarts.
	Seq int64 `json:"seq"`
}

// VolumeMount Volume mount configuration
type VolumeMount struct {
	// NfsTarget Server target address
	NfsTarget string `json:"nfs_target"`

	// Path Mount path inside the sandbox
	Path string `json:"path"`
}

// FilePath defines model for FilePath.
type FilePath = string

// Signature defines model for Signature.
type Signature = string

// SignatureExpiration defines model for SignatureExpiration.
type SignatureExpiration = int

// User defines model for User.
type User = string

// FileNotFound defines model for FileNotFound.
type FileNotFound = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// InvalidPath defines model for InvalidPath.
type InvalidPath = Error

// InvalidUser defines model for InvalidUser.
type InvalidUser = Error

// NotAcceptable defines model for NotAcceptable.
type NotAcceptable = Error

// NotEnoughDiskSpace defines model for NotEnoughDiskSpace.
type NotEnoughDiskSpace = Error

// UploadSuccess defines model for UploadSuccess.
type UploadSuccess = []EntryInfo

// GetFilesParams defines parameters for GetFiles.
type GetFilesParams struct {
	// Path Path to the file, URL encoded. Can be relative to the user's home directory (e.g. "file.txt" resolves to ~/file.txt).
	Path FilePath `form:"path,omitempty" json:"path,omitempty"`

	// Username User for setting file ownership and resolving relative paths. Defaults to the sandbox's default user.
	Username User `form:"username,omitempty" json:"username,omitempty"`

	// Signature Signature used for file access permission verification.
	Signature Signature `form:"signature,omitempty" json:"signature,omitempty"`

	// SignatureExpiration Unix timestamp (seconds) after which the signature expires. Only used with the signature parameter.
	SignatureExpiration SignatureExpiration `form:"signature_expiration,omitempty" json:"signature_expiration,omitempty"`
}

// PostFilesMultipartBody defines parameters for PostFiles.
type PostFilesMultipartBody struct {
	File openapi_types.File `json:"file,omitempty"`
}

// PostFilesParams defines parameters for PostFiles.
type PostFilesParams struct {
	// Path Path to the file, URL encoded. Can be relative to the user's home directory (e.g. "file.txt" resolves to ~/file.txt).
	Path FilePath `form:"path,omitempty" json:"path,omitempty"`

	// Username User for setting file ownership and resolving relative paths. Defaults to the sandbox's default user.
	Username User `form:"username,omitempty" json:"username,omitempty"`

	// Signature Signature used for file access permission verification.
	Signature Signature `form:"signature,omitempty" json:"signature,omitempty"`

	// SignatureExpiration Unix timestamp (seconds) after which the signature expires. Only used with the signature parameter.
	SignatureExpiration SignatureExpiration `form:"signature_expiration,omitempty" json:"signature_expiration,omitempty"`
}

// PostFreezeParams defines parameters for PostFreeze.
type PostFreezeParams struct {
	// Mode Which cgroups to freeze. "hierarchy" freezes the complement of envd's own
	// ancestor chain, so cgroups the customer created anywhere in the tree are
	// covered; "legacy" freezes only the user and pty cgroups envd itself creates.
	// Omitted means legacy, which is what an orchestrator predating this parameter
	// gets.
	//
	// The mode is chosen by the caller because the feature flag that selects it is
	// evaluated there — envd has no access to it. FreezeResult echoes the mode back
	// so the caller can confirm envd honoured the request rather than inferring it
	// from the flag's value: an envd too old to know about modes reports legacy
	// while the flag reads on.
	Mode PostFreezeParamsMode `form:"mode,omitempty" json:"mode,omitempty"`

	// MaxCgroups Bounds how many cgroups a hierarchy sweep may visit. A safety guard against a
	// pathological or hostile hierarchy rather than a performance knob — the guest is
	// the threat model. Omitted or non-positive means envd's own default. Ignored in
	// legacy mode.
	MaxCgroups int `form:"maxCgroups,omitempty" json:"maxCgroups,omitempty"`

	// MaxWaitMs How long to wait for the cgroups to read back frozen, in milliseconds. The
	// caller owns this budget because it also owns the request timeout, and a wait
	// longer than that timeout cannot be observed.
	//
	// Supplying it also selects the response: with it, the call waits and answers 200
	// with a FreezeResult; omitted or non-positive, the call does not wait at all and
	// answers 204, which is the contract callers older than this parameter expect.
	MaxWaitMs int64 `form:"maxWaitMs,omitempty" json:"maxWaitMs,omitempty"`
}

// PostFreezeParamsMode defines parameters for PostFreeze.
type PostFreezeParamsMode string

// PostInitJSONBody defines parameters for PostInit.
type PostInitJSONBody struct {
	// AccessToken Access token for secure access to envd service
	AccessToken SecureToken `json:"accessToken,omitempty"`

	// CaBundle PEM-encoded CA certificates to install into the system trust store (may contain multiple concatenated PEM blocks)
	CaBundle string `json:"caBundle,omitempty"`

	// CpuCount Number of guest CPUs that should be online. envd attempts to bring the set of requested CPUs online asynchronously; the outcome is reported on the X-Envd-Cpus header and on /metrics.
	CpuCount int `json:"cpuCount,omitempty"`

	// DefaultUser The default user to use for operations
	DefaultUser string `json:"defaultUser,omitempty"`

	// DefaultWorkdir The default working directory to use for operations
	DefaultWorkdir string `json:"defaultWorkdir,omitempty"`

	// EnvVars Environment variables to set
	EnvVars EnvVars `json:"envVars,omitempty"`

	// HyperloopIP IP address of the hyperloop server to connect to
	HyperloopIP string `json:"hyperloopIP,omitempty"`

	// LifecycleID Lifecycle ID of the sandbox
	LifecycleID string `json:"lifecycleID,omitempty"`

	// Thaw Whether this call thaws the workload cgroups a pre-pause freeze left frozen. Absent or "inline": it thaws them before it answers, as every envd before this field did, unless a freeze came after the call entered, which the call then leaves in place. "skip": it thaws nothing and answers X-Envd-Thaw: skip, leaving the workload frozen; only for a resume whose VM is discarded after the call, such as one that records which pages the resume touches. A value this envd does not know reads as inline, the side on which a guest is never left frozen.
	Thaw PostInitJSONBodyThaw `json:"thaw,omitempty"`

	// Timestamp The current timestamp in RFC3339 format. envd adds its own time from reading the request body to its clock gates, reported on X-Envd-Init-Clock-Correction, and applies its clock rules to the result.
	Timestamp    time.Time     `json:"timestamp,omitempty"`
	VolumeMounts []VolumeMount `json:"volumeMounts,omitempty"`
}

// PostInitJSONBodyThaw defines parameters for PostInit.
type PostInitJSONBodyThaw string

// PostFilesMultipartRequestBody defines body for PostFiles for multipart/form-data ContentType.
type PostFilesMultipartRequestBody PostFilesMultipartBody

// PostFilesComposeJSONRequestBody defines body for PostFilesCompose for application/json ContentType.
type PostFilesComposeJSONRequestBody = ComposeRequest

// PostInitJSONRequestBody defines body for PostInit for application/json ContentType.
type PostInitJSONRequestBody PostInitJSONBody
