// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_profiles.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyBillingProfileProjection = `-- name: ApplyBillingProfileProjection :one
WITH changed AS (
    INSERT INTO projection.billing_profiles (project_id, revision, decided_at)
    VALUES (
        $1::uuid,
        $2::bigint,
        $3::timestamptz
    )
    ON CONFLICT (project_id) DO UPDATE
    SET
        revision = EXCLUDED.revision,
        decided_at = EXCLUDED.decided_at,
        updated_at = now()
    WHERE projection.billing_profiles.revision < EXCLUDED.revision
    RETURNING project_id
)
SELECT EXISTS (SELECT 1 FROM changed) AS applied
`

type ApplyBillingProfileProjectionParams struct {
	ProjectID uuid.UUID
	Revision  int64
	DecidedAt *time.Time
}

// Advance in the same transaction as team_billing_profiles so retries cannot
// skip an unwritten state. Same fence as ApplyProjectLimitsProjection.
func (q *Queries) ApplyBillingProfileProjection(ctx context.Context, arg ApplyBillingProfileProjectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, applyBillingProfileProjection, arg.ProjectID, arg.Revision, arg.DecidedAt)
	var applied bool
	err := row.Scan(&applied)
	return applied, err
}

const upsertTeamBillingProfile = `-- name: UpsertTeamBillingProfile :exec
INSERT INTO public.team_billing_profiles (
    team_id,
    has_payment_method,
    enterprise,
    plan,
    updated_at
) VALUES (
    $1::uuid,
    $2::boolean,
    $3::boolean,
    $4::text,
    now()
)
ON CONFLICT (team_id) DO UPDATE SET
    has_payment_method = EXCLUDED.has_payment_method,
    enterprise         = EXCLUDED.enterprise,
    plan               = EXCLUDED.plan,
    updated_at         = now()
`

type UpsertTeamBillingProfileParams struct {
	TeamID           uuid.UUID
	HasPaymentMethod bool
	Enterprise       bool
	Plan             *string
}

// Every column is supplied on every call: the caller sends a complete profile,
// so there is no partial update to merge. Which deliveries reach this statement
// is the ledger's decision; nothing here compares revisions.
func (q *Queries) UpsertTeamBillingProfile(ctx context.Context, arg UpsertTeamBillingProfileParams) error {
	_, err := q.db.Exec(ctx, upsertTeamBillingProfile,
		arg.TeamID,
		arg.HasPaymentMethod,
		arg.Enterprise,
		arg.Plan,
	)
	return err
}
