// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cathedral_sandbox_lifecycle_operations.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeCathedralSandboxLifecycleOperation = `-- name: CompleteCathedralSandboxLifecycleOperation :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'completed',
    execution_removed_at = $1::timestamptz,
    snapshot_build_id = $2::text,
    snapshot_completed_at = $3::timestamptz,
    cleanup_state = $4::text,
    result_json = $5::text,
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE team_id = $6::uuid
  AND operation_key = $7::text
  AND request_sha256 = $8::text
  AND operation_kind = $9::text
  AND sandbox_id = $10::text
  AND execution_id = $11::text
  AND state = 'dispatching'
`

type CompleteCathedralSandboxLifecycleOperationParams struct {
	ExecutionRemovedAt  time.Time
	SnapshotBuildID     *string
	SnapshotCompletedAt *time.Time
	CleanupState        string
	ResultJson          string
	TeamID              uuid.UUID
	OperationKey        string
	RequestSha256       string
	OperationKind       string
	SandboxID           string
	ExecutionID         string
}

func (q *Queries) CompleteCathedralSandboxLifecycleOperation(ctx context.Context, arg CompleteCathedralSandboxLifecycleOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCathedralSandboxLifecycleOperation,
		arg.ExecutionRemovedAt,
		arg.SnapshotBuildID,
		arg.SnapshotCompletedAt,
		arg.CleanupState,
		arg.ResultJson,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failCathedralSandboxLifecycleOperation = `-- name: FailCathedralSandboxLifecycleOperation :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'failed', error_code = $1::integer,
    error_message = $2::text, updated_at = now()
WHERE team_id = $3::uuid
  AND operation_key = $4::text
  AND request_sha256 = $5::text
  AND operation_kind = $6::text
  AND sandbox_id = $7::text
  AND execution_id = $8::text
  AND state IN ('reserved', 'dispatching', 'failed')
`

type FailCathedralSandboxLifecycleOperationParams struct {
	ErrorCode     int32
	ErrorMessage  string
	TeamID        uuid.UUID
	OperationKey  string
	RequestSha256 string
	OperationKind string
	SandboxID     string
	ExecutionID   string
}

func (q *Queries) FailCathedralSandboxLifecycleOperation(ctx context.Context, arg FailCathedralSandboxLifecycleOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failCathedralSandboxLifecycleOperation,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCathedralSandboxLifecycleOperation = `-- name: GetCathedralSandboxLifecycleOperation :one
SELECT team_id, operation_key, request_sha256, operation_kind, sandbox_id, execution_id, state, execution_removed_at, snapshot_build_id, snapshot_completed_at, remaining_lifetime_ms, cleanup_state, result_json, error_code, error_message, created_at, dispatch_started_at, updated_at
FROM public.cathedral_sandbox_lifecycle_operations
WHERE team_id = $1::uuid
  AND operation_key = $2::text
`

type GetCathedralSandboxLifecycleOperationParams struct {
	TeamID       uuid.UUID
	OperationKey string
}

func (q *Queries) GetCathedralSandboxLifecycleOperation(ctx context.Context, arg GetCathedralSandboxLifecycleOperationParams) (CathedralSandboxLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, getCathedralSandboxLifecycleOperation, arg.TeamID, arg.OperationKey)
	var i CathedralSandboxLifecycleOperation
	err := row.Scan(
		&i.TeamID,
		&i.OperationKey,
		&i.RequestSha256,
		&i.OperationKind,
		&i.SandboxID,
		&i.ExecutionID,
		&i.State,
		&i.ExecutionRemovedAt,
		&i.SnapshotBuildID,
		&i.SnapshotCompletedAt,
		&i.RemainingLifetimeMs,
		&i.CleanupState,
		&i.ResultJson,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchStartedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCathedralSandboxLifecycleDispatching = `-- name: MarkCathedralSandboxLifecycleDispatching :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'dispatching', dispatch_started_at = COALESCE(dispatch_started_at, now()), updated_at = now()
WHERE team_id = $1::uuid
  AND operation_key = $2::text
  AND request_sha256 = $3::text
  AND operation_kind = $4::text
  AND sandbox_id = $5::text
  AND execution_id = $6::text
  AND state = 'reserved'
`

type MarkCathedralSandboxLifecycleDispatchingParams struct {
	TeamID        uuid.UUID
	OperationKey  string
	RequestSha256 string
	OperationKind string
	SandboxID     string
	ExecutionID   string
}

func (q *Queries) MarkCathedralSandboxLifecycleDispatching(ctx context.Context, arg MarkCathedralSandboxLifecycleDispatchingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCathedralSandboxLifecycleDispatching,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCathedralSandboxLifecycleUnknown = `-- name: MarkCathedralSandboxLifecycleUnknown :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'unknown', error_code = $1::integer,
    error_message = $2::text, updated_at = now()
WHERE team_id = $3::uuid
  AND operation_key = $4::text
  AND request_sha256 = $5::text
  AND operation_kind = $6::text
  AND sandbox_id = $7::text
  AND execution_id = $8::text
  AND state IN ('reserved', 'dispatching', 'unknown')
`

type MarkCathedralSandboxLifecycleUnknownParams struct {
	ErrorCode     *int32
	ErrorMessage  string
	TeamID        uuid.UUID
	OperationKey  string
	RequestSha256 string
	OperationKind string
	SandboxID     string
	ExecutionID   string
}

func (q *Queries) MarkCathedralSandboxLifecycleUnknown(ctx context.Context, arg MarkCathedralSandboxLifecycleUnknownParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCathedralSandboxLifecycleUnknown,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveCathedralSandboxLifecycleOperation = `-- name: ReserveCathedralSandboxLifecycleOperation :one
INSERT INTO public.cathedral_sandbox_lifecycle_operations (
    team_id, operation_key, request_sha256, operation_kind, sandbox_id,
    execution_id, remaining_lifetime_ms, cleanup_state
) VALUES (
    $1::uuid, $2::text,
    $3::text, $4::text,
    $5::text, $6::text,
    $7::bigint,
    CASE WHEN $4::text = 'delete' THEN 'pending' ELSE 'not_required' END
)
ON CONFLICT (team_id, operation_key) DO NOTHING
RETURNING team_id, operation_key, request_sha256, operation_kind, sandbox_id, execution_id, state, execution_removed_at, snapshot_build_id, snapshot_completed_at, remaining_lifetime_ms, cleanup_state, result_json, error_code, error_message, created_at, dispatch_started_at, updated_at
`

type ReserveCathedralSandboxLifecycleOperationParams struct {
	TeamID              uuid.UUID
	OperationKey        string
	RequestSha256       string
	OperationKind       string
	SandboxID           string
	ExecutionID         string
	RemainingLifetimeMs *int64
}

func (q *Queries) ReserveCathedralSandboxLifecycleOperation(ctx context.Context, arg ReserveCathedralSandboxLifecycleOperationParams) (CathedralSandboxLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, reserveCathedralSandboxLifecycleOperation,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
		arg.RemainingLifetimeMs,
	)
	var i CathedralSandboxLifecycleOperation
	err := row.Scan(
		&i.TeamID,
		&i.OperationKey,
		&i.RequestSha256,
		&i.OperationKind,
		&i.SandboxID,
		&i.ExecutionID,
		&i.State,
		&i.ExecutionRemovedAt,
		&i.SnapshotBuildID,
		&i.SnapshotCompletedAt,
		&i.RemainingLifetimeMs,
		&i.CleanupState,
		&i.ResultJson,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchStartedAt,
		&i.UpdatedAt,
	)
	return i, err
}
