// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cathedral_sandbox_lifecycle_operations.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeCathedralSandboxLifecycleOperation = `-- name: CompleteCathedralSandboxLifecycleOperation :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'completed',
    execution_removed_at = $1::timestamptz,
    snapshot_build_id = $2::text,
    snapshot_completed_at = $3::timestamptz,
    cleanup_state = $4::text,
    remaining_lifetime_ms = $5::bigint,
    dispatch_lease_expires_at = NULL,
    result_json = $6::text,
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE team_id = $7::uuid
  AND operation_key = $8::text
  AND request_sha256 = $9::text
  AND operation_kind = $10::text
  AND sandbox_id = $11::text
  AND execution_id = $12::text
  AND dispatch_attempt = $13::integer
  AND state = 'dispatching'
`

type CompleteCathedralSandboxLifecycleOperationParams struct {
	ExecutionRemovedAt  time.Time
	SnapshotBuildID     *string
	SnapshotCompletedAt *time.Time
	CleanupState        string
	RemainingLifetimeMs *int64
	ResultJson          string
	TeamID              uuid.UUID
	OperationKey        string
	RequestSha256       string
	OperationKind       string
	SandboxID           string
	ExecutionID         string
	DispatchAttempt     int32
}

func (q *Queries) CompleteCathedralSandboxLifecycleOperation(ctx context.Context, arg CompleteCathedralSandboxLifecycleOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCathedralSandboxLifecycleOperation,
		arg.ExecutionRemovedAt,
		arg.SnapshotBuildID,
		arg.SnapshotCompletedAt,
		arg.CleanupState,
		arg.RemainingLifetimeMs,
		arg.ResultJson,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
		arg.DispatchAttempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failCathedralSandboxLifecycleOperation = `-- name: FailCathedralSandboxLifecycleOperation :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'failed', dispatch_lease_expires_at = NULL,
    error_code = $1::integer,
    error_message = $2::text, updated_at = now()
WHERE team_id = $3::uuid
  AND operation_key = $4::text
  AND request_sha256 = $5::text
  AND operation_kind = $6::text
  AND sandbox_id = $7::text
  AND execution_id = $8::text
  AND (state <> 'dispatching' OR dispatch_attempt = $9::integer)
  AND state IN ('reserved', 'dispatching', 'failed')
`

type FailCathedralSandboxLifecycleOperationParams struct {
	ErrorCode       int32
	ErrorMessage    string
	TeamID          uuid.UUID
	OperationKey    string
	RequestSha256   string
	OperationKind   string
	SandboxID       string
	ExecutionID     string
	DispatchAttempt int32
}

func (q *Queries) FailCathedralSandboxLifecycleOperation(ctx context.Context, arg FailCathedralSandboxLifecycleOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failCathedralSandboxLifecycleOperation,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
		arg.DispatchAttempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCathedralSandboxLifecycleOperation = `-- name: GetCathedralSandboxLifecycleOperation :one
SELECT team_id, operation_key, request_sha256, operation_kind, sandbox_id, execution_id, state, execution_removed_at, snapshot_build_id, snapshot_completed_at, remaining_lifetime_ms, cleanup_state, result_json, error_code, error_message, created_at, dispatch_started_at, updated_at, filesystem_only, dispatch_attempt, dispatch_lease_expires_at
FROM public.cathedral_sandbox_lifecycle_operations
WHERE team_id = $1::uuid
  AND operation_key = $2::text
`

type GetCathedralSandboxLifecycleOperationParams struct {
	TeamID       uuid.UUID
	OperationKey string
}

func (q *Queries) GetCathedralSandboxLifecycleOperation(ctx context.Context, arg GetCathedralSandboxLifecycleOperationParams) (CathedralSandboxLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, getCathedralSandboxLifecycleOperation, arg.TeamID, arg.OperationKey)
	var i CathedralSandboxLifecycleOperation
	err := row.Scan(
		&i.TeamID,
		&i.OperationKey,
		&i.RequestSha256,
		&i.OperationKind,
		&i.SandboxID,
		&i.ExecutionID,
		&i.State,
		&i.ExecutionRemovedAt,
		&i.SnapshotBuildID,
		&i.SnapshotCompletedAt,
		&i.RemainingLifetimeMs,
		&i.CleanupState,
		&i.ResultJson,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchStartedAt,
		&i.UpdatedAt,
		&i.FilesystemOnly,
		&i.DispatchAttempt,
		&i.DispatchLeaseExpiresAt,
	)
	return i, err
}

const markCathedralSandboxLifecycleDispatching = `-- name: MarkCathedralSandboxLifecycleDispatching :one
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'dispatching', dispatch_started_at = now(),
    dispatch_attempt = dispatch_attempt + 1,
    dispatch_lease_expires_at = now() + $1::interval,
    error_code = NULL, error_message = NULL, updated_at = now()
WHERE team_id = $2::uuid
  AND operation_key = $3::text
  AND request_sha256 = $4::text
  AND operation_kind = $5::text
  AND sandbox_id = $6::text
  AND execution_id = $7::text
  AND state = 'reserved'
RETURNING team_id, operation_key, request_sha256, operation_kind, sandbox_id, execution_id, state, execution_removed_at, snapshot_build_id, snapshot_completed_at, remaining_lifetime_ms, cleanup_state, result_json, error_code, error_message, created_at, dispatch_started_at, updated_at, filesystem_only, dispatch_attempt, dispatch_lease_expires_at
`

type MarkCathedralSandboxLifecycleDispatchingParams struct {
	LeaseDuration pgtype.Interval
	TeamID        uuid.UUID
	OperationKey  string
	RequestSha256 string
	OperationKind string
	SandboxID     string
	ExecutionID   string
}

func (q *Queries) MarkCathedralSandboxLifecycleDispatching(ctx context.Context, arg MarkCathedralSandboxLifecycleDispatchingParams) (CathedralSandboxLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, markCathedralSandboxLifecycleDispatching,
		arg.LeaseDuration,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
	)
	var i CathedralSandboxLifecycleOperation
	err := row.Scan(
		&i.TeamID,
		&i.OperationKey,
		&i.RequestSha256,
		&i.OperationKind,
		&i.SandboxID,
		&i.ExecutionID,
		&i.State,
		&i.ExecutionRemovedAt,
		&i.SnapshotBuildID,
		&i.SnapshotCompletedAt,
		&i.RemainingLifetimeMs,
		&i.CleanupState,
		&i.ResultJson,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchStartedAt,
		&i.UpdatedAt,
		&i.FilesystemOnly,
		&i.DispatchAttempt,
		&i.DispatchLeaseExpiresAt,
	)
	return i, err
}

const markCathedralSandboxLifecycleUnknown = `-- name: MarkCathedralSandboxLifecycleUnknown :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'unknown', dispatch_lease_expires_at = NULL,
    error_code = $1::integer,
    error_message = $2::text, updated_at = now()
WHERE team_id = $3::uuid
  AND operation_key = $4::text
  AND request_sha256 = $5::text
  AND operation_kind = $6::text
  AND sandbox_id = $7::text
  AND execution_id = $8::text
  AND dispatch_attempt = $9::integer
  AND state IN ('reserved', 'dispatching', 'unknown')
`

type MarkCathedralSandboxLifecycleUnknownParams struct {
	ErrorCode       *int32
	ErrorMessage    string
	TeamID          uuid.UUID
	OperationKey    string
	RequestSha256   string
	OperationKind   string
	SandboxID       string
	ExecutionID     string
	DispatchAttempt int32
}

func (q *Queries) MarkCathedralSandboxLifecycleUnknown(ctx context.Context, arg MarkCathedralSandboxLifecycleUnknownParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCathedralSandboxLifecycleUnknown,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
		arg.DispatchAttempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueCathedralSandboxLifecycleDispatch = `-- name: RequeueCathedralSandboxLifecycleDispatch :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'reserved', dispatch_lease_expires_at = NULL,
    error_code = $1::integer,
    error_message = $2::text, updated_at = now()
WHERE team_id = $3::uuid
  AND operation_key = $4::text
  AND request_sha256 = $5::text
  AND execution_id = $6::text
  AND state = 'dispatching'
  AND dispatch_attempt = $7::integer
`

type RequeueCathedralSandboxLifecycleDispatchParams struct {
	ErrorCode       *int32
	ErrorMessage    string
	TeamID          uuid.UUID
	OperationKey    string
	RequestSha256   string
	ExecutionID     string
	DispatchAttempt int32
}

func (q *Queries) RequeueCathedralSandboxLifecycleDispatch(ctx context.Context, arg RequeueCathedralSandboxLifecycleDispatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueCathedralSandboxLifecycleDispatch,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.ExecutionID,
		arg.DispatchAttempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueExpiredCathedralSandboxLifecycleDispatch = `-- name: RequeueExpiredCathedralSandboxLifecycleDispatch :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET state = 'reserved', dispatch_lease_expires_at = NULL,
    error_code = $1::integer,
    error_message = $2::text, updated_at = now()
WHERE team_id = $3::uuid
  AND operation_key = $4::text
  AND request_sha256 = $5::text
  AND execution_id = $6::text
  AND state = 'dispatching'
  AND dispatch_attempt = $7::integer
  AND dispatch_lease_expires_at <= now()
`

type RequeueExpiredCathedralSandboxLifecycleDispatchParams struct {
	ErrorCode       *int32
	ErrorMessage    string
	TeamID          uuid.UUID
	OperationKey    string
	RequestSha256   string
	ExecutionID     string
	DispatchAttempt int32
}

func (q *Queries) RequeueExpiredCathedralSandboxLifecycleDispatch(ctx context.Context, arg RequeueExpiredCathedralSandboxLifecycleDispatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueExpiredCathedralSandboxLifecycleDispatch,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.ExecutionID,
		arg.DispatchAttempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveCathedralSandboxLifecycleOperation = `-- name: ReserveCathedralSandboxLifecycleOperation :one
INSERT INTO public.cathedral_sandbox_lifecycle_operations (
    team_id, operation_key, request_sha256, operation_kind, sandbox_id,
    execution_id, filesystem_only, remaining_lifetime_ms, cleanup_state
) VALUES (
    $1::uuid, $2::text,
    $3::text, $4::text,
    $5::text, $6::text,
    $7::boolean,
    $8::bigint,
    CASE WHEN $4::text = 'delete' THEN 'pending' ELSE 'not_required' END
)
ON CONFLICT (team_id, operation_key) DO NOTHING
RETURNING team_id, operation_key, request_sha256, operation_kind, sandbox_id, execution_id, state, execution_removed_at, snapshot_build_id, snapshot_completed_at, remaining_lifetime_ms, cleanup_state, result_json, error_code, error_message, created_at, dispatch_started_at, updated_at, filesystem_only, dispatch_attempt, dispatch_lease_expires_at
`

type ReserveCathedralSandboxLifecycleOperationParams struct {
	TeamID              uuid.UUID
	OperationKey        string
	RequestSha256       string
	OperationKind       string
	SandboxID           string
	ExecutionID         string
	FilesystemOnly      bool
	RemainingLifetimeMs *int64
}

func (q *Queries) ReserveCathedralSandboxLifecycleOperation(ctx context.Context, arg ReserveCathedralSandboxLifecycleOperationParams) (CathedralSandboxLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, reserveCathedralSandboxLifecycleOperation,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.OperationKind,
		arg.SandboxID,
		arg.ExecutionID,
		arg.FilesystemOnly,
		arg.RemainingLifetimeMs,
	)
	var i CathedralSandboxLifecycleOperation
	err := row.Scan(
		&i.TeamID,
		&i.OperationKey,
		&i.RequestSha256,
		&i.OperationKind,
		&i.SandboxID,
		&i.ExecutionID,
		&i.State,
		&i.ExecutionRemovedAt,
		&i.SnapshotBuildID,
		&i.SnapshotCompletedAt,
		&i.RemainingLifetimeMs,
		&i.CleanupState,
		&i.ResultJson,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchStartedAt,
		&i.UpdatedAt,
		&i.FilesystemOnly,
		&i.DispatchAttempt,
		&i.DispatchLeaseExpiresAt,
	)
	return i, err
}

const updateCathedralSandboxLifecycleCleanup = `-- name: UpdateCathedralSandboxLifecycleCleanup :execrows
UPDATE public.cathedral_sandbox_lifecycle_operations
SET cleanup_state = $1::text, updated_at = now()
WHERE team_id = $2::uuid
  AND operation_key = $3::text
  AND request_sha256 = $4::text
  AND operation_kind = 'delete'
  AND sandbox_id = $5::text
  AND execution_id = $6::text
  AND state = 'completed'
  AND cleanup_state IN ('pending', 'failed')
`

type UpdateCathedralSandboxLifecycleCleanupParams struct {
	CleanupState  string
	TeamID        uuid.UUID
	OperationKey  string
	RequestSha256 string
	SandboxID     string
	ExecutionID   string
}

func (q *Queries) UpdateCathedralSandboxLifecycleCleanup(ctx context.Context, arg UpdateCathedralSandboxLifecycleCleanupParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCathedralSandboxLifecycleCleanup,
		arg.CleanupState,
		arg.TeamID,
		arg.OperationKey,
		arg.RequestSha256,
		arg.SandboxID,
		arg.ExecutionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
