// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cathedral_sandbox_operations.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const completeCathedralSandboxOperation = `-- name: CompleteCathedralSandboxOperation :execrows
UPDATE public.cathedral_sandbox_operations
SET state = 'ready',
    response_json = CASE
        WHEN state = 'ready' THEN response_json
        ELSE $1::text
    END,
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE team_id = $2::uuid
  AND idempotency_key = $3::text
  AND request_sha256 = $4::text
  AND sandbox_id = $5::text
  AND (
      state IN ('reserved', 'creating')
      OR (state = 'ready' AND response_json = $1::text)
  )
`

type CompleteCathedralSandboxOperationParams struct {
	ResponseJson   string
	TeamID         uuid.UUID
	IdempotencyKey string
	RequestSha256  string
	SandboxID      string
}

func (q *Queries) CompleteCathedralSandboxOperation(ctx context.Context, arg CompleteCathedralSandboxOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCathedralSandboxOperation,
		arg.ResponseJson,
		arg.TeamID,
		arg.IdempotencyKey,
		arg.RequestSha256,
		arg.SandboxID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failCathedralSandboxOperation = `-- name: FailCathedralSandboxOperation :execrows
UPDATE public.cathedral_sandbox_operations
SET state = 'failed',
    error_code = $1::integer,
    error_message = $2::text,
    updated_at = now()
WHERE team_id = $3::uuid
  AND idempotency_key = $4::text
  AND request_sha256 = $5::text
  AND sandbox_id = $6::text
  AND state IN ('reserved', 'creating', 'failed')
`

type FailCathedralSandboxOperationParams struct {
	ErrorCode      int32
	ErrorMessage   string
	TeamID         uuid.UUID
	IdempotencyKey string
	RequestSha256  string
	SandboxID      string
}

func (q *Queries) FailCathedralSandboxOperation(ctx context.Context, arg FailCathedralSandboxOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failCathedralSandboxOperation,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TeamID,
		arg.IdempotencyKey,
		arg.RequestSha256,
		arg.SandboxID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCathedralSandboxOperation = `-- name: GetCathedralSandboxOperation :one
SELECT team_id, idempotency_key, request_sha256, operation_kind, sandbox_id, state, response_json, error_code, error_message, created_at, updated_at
FROM public.cathedral_sandbox_operations
WHERE team_id = $1::uuid
  AND idempotency_key = $2::text
`

type GetCathedralSandboxOperationParams struct {
	TeamID         uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetCathedralSandboxOperation(ctx context.Context, arg GetCathedralSandboxOperationParams) (CathedralSandboxOperation, error) {
	row := q.db.QueryRow(ctx, getCathedralSandboxOperation, arg.TeamID, arg.IdempotencyKey)
	var i CathedralSandboxOperation
	err := row.Scan(
		&i.TeamID,
		&i.IdempotencyKey,
		&i.RequestSha256,
		&i.OperationKind,
		&i.SandboxID,
		&i.State,
		&i.ResponseJson,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCathedralSandboxOperationCreating = `-- name: MarkCathedralSandboxOperationCreating :execrows
UPDATE public.cathedral_sandbox_operations
SET state = 'creating',
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE team_id = $1::uuid
  AND idempotency_key = $2::text
  AND request_sha256 = $3::text
  AND sandbox_id = $4::text
  AND state IN ('reserved', 'creating')
`

type MarkCathedralSandboxOperationCreatingParams struct {
	TeamID         uuid.UUID
	IdempotencyKey string
	RequestSha256  string
	SandboxID      string
}

func (q *Queries) MarkCathedralSandboxOperationCreating(ctx context.Context, arg MarkCathedralSandboxOperationCreatingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCathedralSandboxOperationCreating,
		arg.TeamID,
		arg.IdempotencyKey,
		arg.RequestSha256,
		arg.SandboxID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveCathedralSandboxOperation = `-- name: ReserveCathedralSandboxOperation :one
INSERT INTO public.cathedral_sandbox_operations (
    team_id,
    idempotency_key,
    request_sha256,
    sandbox_id,
    state
) VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    'reserved'
)
ON CONFLICT (team_id, idempotency_key) DO NOTHING
RETURNING team_id, idempotency_key, request_sha256, operation_kind, sandbox_id, state, response_json, error_code, error_message, created_at, updated_at
`

type ReserveCathedralSandboxOperationParams struct {
	TeamID         uuid.UUID
	IdempotencyKey string
	RequestSha256  string
	SandboxID      string
}

func (q *Queries) ReserveCathedralSandboxOperation(ctx context.Context, arg ReserveCathedralSandboxOperationParams) (CathedralSandboxOperation, error) {
	row := q.db.QueryRow(ctx, reserveCathedralSandboxOperation,
		arg.TeamID,
		arg.IdempotencyKey,
		arg.RequestSha256,
		arg.SandboxID,
	)
	var i CathedralSandboxOperation
	err := row.Scan(
		&i.TeamID,
		&i.IdempotencyKey,
		&i.RequestSha256,
		&i.OperationKind,
		&i.SandboxID,
		&i.State,
		&i.ResponseJson,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
