// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_snapshots_with_cursor.sql

package queries

import (
	"context"
	"time"

	"github.com/e2b-dev/infra/packages/db/pkg/types"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSnapshotsByTemplateWithCursor = `-- name: GetSnapshotsByTemplateWithCursor :many
SELECT COALESCE(ea.aliases, ARRAY[]::text[])::text[] AS aliases, COALESCE(ea.names, ARRAY[]::text[])::text[] AS names,
    snap.created_at, snap.env_id, snap.sandbox_id, snap.id, snap.metadata, snap.base_env_id, snap.sandbox_started_at, snap.env_secure, snap.origin_node_id, snap.allow_internet_access, snap.auto_pause, snap.team_id, snap.config,
    page.build_id,
    page.build_vcpu,
    page.build_ram_mb,
    page.build_total_disk_size_mb,
    page.build_envd_version,
    page.build_created_at
FROM (
    SELECT
        s.id,
        s.sandbox_started_at,
        s.sandbox_id,
        eb.id AS build_id,
        eb.vcpu AS build_vcpu,
        eb.ram_mb AS build_ram_mb,
        eb.total_disk_size_mb AS build_total_disk_size_mb,
        eb.envd_version AS build_envd_version,
        eb.created_at AS build_created_at
    FROM "public"."snapshots" s
    JOIN "public"."active_envs" e ON e.id = s.env_id
    JOIN LATERAL (
        SELECT eb.id, eb.vcpu, eb.ram_mb, eb.total_disk_size_mb, eb.envd_version, eb.created_at
        FROM "public"."env_build_assignments" eba
        JOIN "public"."env_builds" eb ON eb.id = eba.build_id
        WHERE
            eba.env_id = s.env_id
            AND eba.tag = 'default'
            AND eb.status_group = 'ready'
        ORDER BY eba.created_at DESC
        LIMIT 1
    ) eb ON TRUE
    WHERE
        s.team_id = $2
        AND s.base_env_id = $3
        AND CASE
            WHEN $4::jsonb = '{}'::jsonb AND jsonb_typeof(s.metadata) = 'object'
                THEN TRUE
            ELSE s.metadata @> $4
        END
        AND s.sandbox_started_at >= $5::timestamptz
        AND (s.sandbox_started_at, $6::text) < ($7, s.sandbox_id)
    ORDER BY s.sandbox_started_at DESC, s.sandbox_id ASC
    LIMIT $1
) page
JOIN "public"."snapshots" snap ON snap.id = page.id
LEFT JOIN LATERAL (
    SELECT
        ARRAY_AGG(alias ORDER BY alias) AS aliases,
        ARRAY_AGG(CASE WHEN namespace IS NOT NULL THEN namespace || '/' || alias ELSE alias END ORDER BY alias) AS names
    FROM "public"."env_aliases"
    WHERE env_id = snap.base_env_id
) ea ON TRUE
ORDER BY page.sandbox_started_at DESC, page.sandbox_id ASC
`

type GetSnapshotsByTemplateWithCursorParams struct {
	Limit        int32
	TeamID       uuid.UUID
	TemplateID   string
	Metadata     types.JSONBStringMap
	StartedAfter time.Time
	CursorID     string
	CursorTime   pgtype.Timestamptz
}

type GetSnapshotsByTemplateWithCursorRow struct {
	Aliases              []string
	Names                []string
	Snapshot             Snapshot
	BuildID              uuid.UUID
	BuildVcpu            int64
	BuildRamMb           int64
	BuildTotalDiskSizeMb *int64
	BuildEnvdVersion     *string
	BuildCreatedAt       time.Time
}

func (q *Queries) GetSnapshotsByTemplateWithCursor(ctx context.Context, arg GetSnapshotsByTemplateWithCursorParams) ([]GetSnapshotsByTemplateWithCursorRow, error) {
	rows, err := q.db.Query(ctx, getSnapshotsByTemplateWithCursor,
		arg.Limit,
		arg.TeamID,
		arg.TemplateID,
		arg.Metadata,
		arg.StartedAfter,
		arg.CursorID,
		arg.CursorTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSnapshotsByTemplateWithCursorRow
	for rows.Next() {
		var i GetSnapshotsByTemplateWithCursorRow
		if err := rows.Scan(
			&i.Aliases,
			&i.Names,
			&i.Snapshot.CreatedAt,
			&i.Snapshot.EnvID,
			&i.Snapshot.SandboxID,
			&i.Snapshot.ID,
			&i.Snapshot.Metadata,
			&i.Snapshot.BaseEnvID,
			&i.Snapshot.SandboxStartedAt,
			&i.Snapshot.EnvSecure,
			&i.Snapshot.OriginNodeID,
			&i.Snapshot.AllowInternetAccess,
			&i.Snapshot.AutoPause,
			&i.Snapshot.TeamID,
			&i.Snapshot.Config,
			&i.BuildID,
			&i.BuildVcpu,
			&i.BuildRamMb,
			&i.BuildTotalDiskSizeMb,
			&i.BuildEnvdVersion,
			&i.BuildCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshotsByTemplateWithCursorAsc = `-- name: GetSnapshotsByTemplateWithCursorAsc :many
SELECT COALESCE(ea.aliases, ARRAY[]::text[])::text[] AS aliases, COALESCE(ea.names, ARRAY[]::text[])::text[] AS names,
    snap.created_at, snap.env_id, snap.sandbox_id, snap.id, snap.metadata, snap.base_env_id, snap.sandbox_started_at, snap.env_secure, snap.origin_node_id, snap.allow_internet_access, snap.auto_pause, snap.team_id, snap.config,
    page.build_id,
    page.build_vcpu,
    page.build_ram_mb,
    page.build_total_disk_size_mb,
    page.build_envd_version,
    page.build_created_at
FROM (
    SELECT
        s.id,
        s.sandbox_started_at,
        s.sandbox_id,
        eb.id AS build_id,
        eb.vcpu AS build_vcpu,
        eb.ram_mb AS build_ram_mb,
        eb.total_disk_size_mb AS build_total_disk_size_mb,
        eb.envd_version AS build_envd_version,
        eb.created_at AS build_created_at
    FROM "public"."snapshots" s
    JOIN "public"."active_envs" e ON e.id = s.env_id
    JOIN LATERAL (
        SELECT eb.id, eb.vcpu, eb.ram_mb, eb.total_disk_size_mb, eb.envd_version, eb.created_at
        FROM "public"."env_build_assignments" eba
        JOIN "public"."env_builds" eb ON eb.id = eba.build_id
        WHERE
            eba.env_id = s.env_id
            AND eba.tag = 'default'
            AND eb.status_group = 'ready'
        ORDER BY eba.created_at DESC
        LIMIT 1
    ) eb ON TRUE
    WHERE
        s.team_id = $2
        AND s.base_env_id = $3
        AND CASE
            WHEN $4::jsonb = '{}'::jsonb AND jsonb_typeof(s.metadata) = 'object'
                THEN TRUE
            ELSE s.metadata @> $4
        END
        AND s.sandbox_started_at >= $5::timestamptz
        -- The lower bound supplies the timestamp constraint for the ID tie-breaker and
        -- gives the planner an indexable starting point for the ascending scan.
        AND s.sandbox_started_at >= $6
        AND (s.sandbox_started_at > $6 OR s.sandbox_id < $7::text)
    ORDER BY s.sandbox_started_at ASC, s.sandbox_id DESC
    LIMIT $1
) page
JOIN "public"."snapshots" snap ON snap.id = page.id
LEFT JOIN LATERAL (
    SELECT
        ARRAY_AGG(alias ORDER BY alias) AS aliases,
        ARRAY_AGG(CASE WHEN namespace IS NOT NULL THEN namespace || '/' || alias ELSE alias END ORDER BY alias) AS names
    FROM "public"."env_aliases"
    WHERE env_id = snap.base_env_id
) ea ON TRUE
ORDER BY page.sandbox_started_at ASC, page.sandbox_id DESC
`

type GetSnapshotsByTemplateWithCursorAscParams struct {
	Limit        int32
	TeamID       uuid.UUID
	TemplateID   string
	Metadata     types.JSONBStringMap
	StartedAfter time.Time
	CursorTime   pgtype.Timestamptz
	CursorID     string
}

type GetSnapshotsByTemplateWithCursorAscRow struct {
	Aliases              []string
	Names                []string
	Snapshot             Snapshot
	BuildID              uuid.UUID
	BuildVcpu            int64
	BuildRamMb           int64
	BuildTotalDiskSizeMb *int64
	BuildEnvdVersion     *string
	BuildCreatedAt       time.Time
}

func (q *Queries) GetSnapshotsByTemplateWithCursorAsc(ctx context.Context, arg GetSnapshotsByTemplateWithCursorAscParams) ([]GetSnapshotsByTemplateWithCursorAscRow, error) {
	rows, err := q.db.Query(ctx, getSnapshotsByTemplateWithCursorAsc,
		arg.Limit,
		arg.TeamID,
		arg.TemplateID,
		arg.Metadata,
		arg.StartedAfter,
		arg.CursorTime,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSnapshotsByTemplateWithCursorAscRow
	for rows.Next() {
		var i GetSnapshotsByTemplateWithCursorAscRow
		if err := rows.Scan(
			&i.Aliases,
			&i.Names,
			&i.Snapshot.CreatedAt,
			&i.Snapshot.EnvID,
			&i.Snapshot.SandboxID,
			&i.Snapshot.ID,
			&i.Snapshot.Metadata,
			&i.Snapshot.BaseEnvID,
			&i.Snapshot.SandboxStartedAt,
			&i.Snapshot.EnvSecure,
			&i.Snapshot.OriginNodeID,
			&i.Snapshot.AllowInternetAccess,
			&i.Snapshot.AutoPause,
			&i.Snapshot.TeamID,
			&i.Snapshot.Config,
			&i.BuildID,
			&i.BuildVcpu,
			&i.BuildRamMb,
			&i.BuildTotalDiskSizeMb,
			&i.BuildEnvdVersion,
			&i.BuildCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshotsWithCursor = `-- name: GetSnapshotsWithCursor :many
SELECT COALESCE(ea.aliases, ARRAY[]::text[])::text[] AS aliases, COALESCE(ea.names, ARRAY[]::text[])::text[] AS names,
    snap.created_at, snap.env_id, snap.sandbox_id, snap.id, snap.metadata, snap.base_env_id, snap.sandbox_started_at, snap.env_secure, snap.origin_node_id, snap.allow_internet_access, snap.auto_pause, snap.team_id, snap.config,
    page.build_id,
    page.build_vcpu,
    page.build_ram_mb,
    page.build_total_disk_size_mb,
    page.build_envd_version,
    page.build_created_at
FROM (
    SELECT
        s.id,
        s.sandbox_started_at,
        s.sandbox_id,
        eb.id AS build_id,
        eb.vcpu AS build_vcpu,
        eb.ram_mb AS build_ram_mb,
        eb.total_disk_size_mb AS build_total_disk_size_mb,
        eb.envd_version AS build_envd_version,
        eb.created_at AS build_created_at
    FROM "public"."snapshots" s
    JOIN "public"."active_envs" e ON e.id = s.env_id
    JOIN LATERAL (
        SELECT eb.id, eb.vcpu, eb.ram_mb, eb.total_disk_size_mb, eb.envd_version, eb.created_at
        FROM "public"."env_build_assignments" eba
        JOIN "public"."env_builds" eb ON eb.id = eba.build_id
        WHERE
            eba.env_id = s.env_id
            AND eba.tag = 'default'
            AND eb.status_group = 'ready'
        ORDER BY eba.created_at DESC
        LIMIT 1
    ) eb ON TRUE
    WHERE
        s.team_id = $2
        -- The order here is important, we want started_at descending, but sandbox_id ascending
        -- Short-circuit empty filters only for objects; legacy values still use containment.
        AND CASE
            WHEN $3::jsonb = '{}'::jsonb AND jsonb_typeof(s.metadata) = 'object'
                THEN TRUE
            ELSE s.metadata @> $3
        END
        AND s.sandbox_started_at >= $4::timestamptz
        AND (s.sandbox_started_at, $5::text) < ($6, s.sandbox_id)
    ORDER BY s.sandbox_started_at DESC, s.sandbox_id ASC
    LIMIT $1
) page
JOIN "public"."snapshots" snap ON snap.id = page.id
LEFT JOIN LATERAL (
    SELECT
        ARRAY_AGG(alias ORDER BY alias) AS aliases,
        ARRAY_AGG(CASE WHEN namespace IS NOT NULL THEN namespace || '/' || alias ELSE alias END ORDER BY alias) AS names
    FROM "public"."env_aliases"
    WHERE env_id = snap.base_env_id
) ea ON TRUE
ORDER BY page.sandbox_started_at DESC, page.sandbox_id ASC
`

type GetSnapshotsWithCursorParams struct {
	Limit        int32
	TeamID       uuid.UUID
	Metadata     types.JSONBStringMap
	StartedAfter time.Time
	CursorID     string
	CursorTime   pgtype.Timestamptz
}

type GetSnapshotsWithCursorRow struct {
	Aliases              []string
	Names                []string
	Snapshot             Snapshot
	BuildID              uuid.UUID
	BuildVcpu            int64
	BuildRamMb           int64
	BuildTotalDiskSizeMb *int64
	BuildEnvdVersion     *string
	BuildCreatedAt       time.Time
}

// The page subquery leaves out the wide columns, so a sort over a team's snapshots never
// carries their metadata and config; full rows and aliases are fetched for the page alone.
// The build lookup stays inside because it drops snapshots without a ready build, which
// must happen before LIMIT. The outer ORDER BY reads page columns so the planner can keep
// the subquery's order instead of sorting full rows again. All four queries share this shape.
func (q *Queries) GetSnapshotsWithCursor(ctx context.Context, arg GetSnapshotsWithCursorParams) ([]GetSnapshotsWithCursorRow, error) {
	rows, err := q.db.Query(ctx, getSnapshotsWithCursor,
		arg.Limit,
		arg.TeamID,
		arg.Metadata,
		arg.StartedAfter,
		arg.CursorID,
		arg.CursorTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSnapshotsWithCursorRow
	for rows.Next() {
		var i GetSnapshotsWithCursorRow
		if err := rows.Scan(
			&i.Aliases,
			&i.Names,
			&i.Snapshot.CreatedAt,
			&i.Snapshot.EnvID,
			&i.Snapshot.SandboxID,
			&i.Snapshot.ID,
			&i.Snapshot.Metadata,
			&i.Snapshot.BaseEnvID,
			&i.Snapshot.SandboxStartedAt,
			&i.Snapshot.EnvSecure,
			&i.Snapshot.OriginNodeID,
			&i.Snapshot.AllowInternetAccess,
			&i.Snapshot.AutoPause,
			&i.Snapshot.TeamID,
			&i.Snapshot.Config,
			&i.BuildID,
			&i.BuildVcpu,
			&i.BuildRamMb,
			&i.BuildTotalDiskSizeMb,
			&i.BuildEnvdVersion,
			&i.BuildCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshotsWithCursorAsc = `-- name: GetSnapshotsWithCursorAsc :many
SELECT COALESCE(ea.aliases, ARRAY[]::text[])::text[] AS aliases, COALESCE(ea.names, ARRAY[]::text[])::text[] AS names,
    snap.created_at, snap.env_id, snap.sandbox_id, snap.id, snap.metadata, snap.base_env_id, snap.sandbox_started_at, snap.env_secure, snap.origin_node_id, snap.allow_internet_access, snap.auto_pause, snap.team_id, snap.config,
    page.build_id,
    page.build_vcpu,
    page.build_ram_mb,
    page.build_total_disk_size_mb,
    page.build_envd_version,
    page.build_created_at
FROM (
    SELECT
        s.id,
        s.sandbox_started_at,
        s.sandbox_id,
        eb.id AS build_id,
        eb.vcpu AS build_vcpu,
        eb.ram_mb AS build_ram_mb,
        eb.total_disk_size_mb AS build_total_disk_size_mb,
        eb.envd_version AS build_envd_version,
        eb.created_at AS build_created_at
    FROM "public"."snapshots" s
    JOIN "public"."active_envs" e ON e.id = s.env_id
    JOIN LATERAL (
        SELECT eb.id, eb.vcpu, eb.ram_mb, eb.total_disk_size_mb, eb.envd_version, eb.created_at
        FROM "public"."env_build_assignments" eba
        JOIN "public"."env_builds" eb ON eb.id = eba.build_id
        WHERE
            eba.env_id = s.env_id
            AND eba.tag = 'default'
            AND eb.status_group = 'ready'
        ORDER BY eba.created_at DESC
        LIMIT 1
    ) eb ON TRUE
    WHERE
        s.team_id = $2
        AND CASE
            WHEN $3::jsonb = '{}'::jsonb AND jsonb_typeof(s.metadata) = 'object'
                THEN TRUE
            ELSE s.metadata @> $3
        END
        AND s.sandbox_started_at >= $4::timestamptz
        -- The lower bound supplies the timestamp constraint for the ID tie-breaker and
        -- gives the planner an indexable starting point for the ascending scan.
        AND s.sandbox_started_at >= $5
        AND (s.sandbox_started_at > $5 OR s.sandbox_id < $6::text)
    ORDER BY s.sandbox_started_at ASC, s.sandbox_id DESC
    LIMIT $1
) page
JOIN "public"."snapshots" snap ON snap.id = page.id
LEFT JOIN LATERAL (
    SELECT
        ARRAY_AGG(alias ORDER BY alias) AS aliases,
        ARRAY_AGG(CASE WHEN namespace IS NOT NULL THEN namespace || '/' || alias ELSE alias END ORDER BY alias) AS names
    FROM "public"."env_aliases"
    WHERE env_id = snap.base_env_id
) ea ON TRUE
ORDER BY page.sandbox_started_at ASC, page.sandbox_id DESC
`

type GetSnapshotsWithCursorAscParams struct {
	Limit        int32
	TeamID       uuid.UUID
	Metadata     types.JSONBStringMap
	StartedAfter time.Time
	CursorTime   pgtype.Timestamptz
	CursorID     string
}

type GetSnapshotsWithCursorAscRow struct {
	Aliases              []string
	Names                []string
	Snapshot             Snapshot
	BuildID              uuid.UUID
	BuildVcpu            int64
	BuildRamMb           int64
	BuildTotalDiskSizeMb *int64
	BuildEnvdVersion     *string
	BuildCreatedAt       time.Time
}

// Ascending counterpart of GetSnapshotsWithCursor. It is the exact reverse order
// (started_at ASC, sandbox_id DESC) which maps onto a backward scan of the
// idx_snapshots_team_time_id (team_id, sandbox_started_at DESC, sandbox_id) index.
func (q *Queries) GetSnapshotsWithCursorAsc(ctx context.Context, arg GetSnapshotsWithCursorAscParams) ([]GetSnapshotsWithCursorAscRow, error) {
	rows, err := q.db.Query(ctx, getSnapshotsWithCursorAsc,
		arg.Limit,
		arg.TeamID,
		arg.Metadata,
		arg.StartedAfter,
		arg.CursorTime,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSnapshotsWithCursorAscRow
	for rows.Next() {
		var i GetSnapshotsWithCursorAscRow
		if err := rows.Scan(
			&i.Aliases,
			&i.Names,
			&i.Snapshot.CreatedAt,
			&i.Snapshot.EnvID,
			&i.Snapshot.SandboxID,
			&i.Snapshot.ID,
			&i.Snapshot.Metadata,
			&i.Snapshot.BaseEnvID,
			&i.Snapshot.SandboxStartedAt,
			&i.Snapshot.EnvSecure,
			&i.Snapshot.OriginNodeID,
			&i.Snapshot.AllowInternetAccess,
			&i.Snapshot.AutoPause,
			&i.Snapshot.TeamID,
			&i.Snapshot.Config,
			&i.BuildID,
			&i.BuildVcpu,
			&i.BuildRamMb,
			&i.BuildTotalDiskSizeMb,
			&i.BuildEnvdVersion,
			&i.BuildCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
