// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_snapshot_filesystem_only.sql

package queries

import (
	"context"
)

const getSnapshotFilesystemOnly = `-- name: GetSnapshotFilesystemOnly :one
SELECT COALESCE((config->>'filesystemOnly')::boolean, FALSE)::boolean AS filesystem_only
FROM "public"."snapshots"
WHERE sandbox_id = $1
`

// The kind recorded on a sandbox's snapshot row, false when the row predates
// the config column. No row is a not-found error the caller treats as false.
func (q *Queries) GetSnapshotFilesystemOnly(ctx context.Context, sandboxID string) (bool, error) {
	row := q.db.QueryRow(ctx, getSnapshotFilesystemOnly, sandboxID)
	var filesystem_only bool
	err := row.Scan(&filesystem_only)
	return filesystem_only, err
}
