// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_blocks.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const applyProjectBlockProjection = `-- name: ApplyProjectBlockProjection :one
WITH changed AS (
    INSERT INTO projection.project_blocks (project_id, revision)
    VALUES (
        $1::uuid,
        $2::bigint
    )
    ON CONFLICT (project_id) DO UPDATE
    SET
        revision = EXCLUDED.revision,
        updated_at = now()
    WHERE projection.project_blocks.revision < EXCLUDED.revision
    RETURNING project_id
)
SELECT EXISTS (SELECT 1 FROM changed) AS applied
`

type ApplyProjectBlockProjectionParams struct {
	ProjectID uuid.UUID
	Revision  int64
}

// Advance in the same transaction as teams.is_blocked so retries cannot skip an unwritten state.
func (q *Queries) ApplyProjectBlockProjection(ctx context.Context, arg ApplyProjectBlockProjectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, applyProjectBlockProjection, arg.ProjectID, arg.Revision)
	var applied bool
	err := row.Scan(&applied)
	return applied, err
}
