// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_snapshot_filesystem_only.sql

package queries

import (
	"context"
)

const updateSnapshotFilesystemOnly = `-- name: UpdateSnapshotFilesystemOnly :exec
UPDATE "public"."snapshots"
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{filesystemOnly}', to_jsonb($1::boolean))
WHERE sandbox_id = $2
`

type UpdateSnapshotFilesystemOnlyParams struct {
	FilesystemOnly bool
	SandboxID      string
}

// Records the kind of the build that just became the row's latest ready one.
// Written on success only, so a refused or failed checkpoint never changes
// what the previous ready build is resumed as.
func (q *Queries) UpdateSnapshotFilesystemOnly(ctx context.Context, arg UpdateSnapshotFilesystemOnlyParams) error {
	_, err := q.db.Exec(ctx, updateSnapshotFilesystemOnly, arg.FilesystemOnly, arg.SandboxID)
	return err
}
