// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build linux

package peerservermocks

import (
	"context"

	"github.com/e2b-dev/infra/packages/orchestrator/pkg/sandbox/build"
	"github.com/e2b-dev/infra/packages/orchestrator/pkg/sandbox/template"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// LookupDiff provides a mock function for the type MockCache
func (_mock *MockCache) LookupDiff(buildID string, diffType build.DiffType) (build.Diff, bool) {
	ret := _mock.Called(buildID, diffType)

	if len(ret) == 0 {
		panic("no return value specified for LookupDiff")
	}

	var r0 build.Diff
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, build.DiffType) (build.Diff, bool)); ok {
		return returnFunc(buildID, diffType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, build.DiffType) build.Diff); ok {
		r0 = returnFunc(buildID, diffType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(build.Diff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, build.DiffType) bool); ok {
		r1 = returnFunc(buildID, diffType)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockCache_LookupDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupDiff'
type MockCache_LookupDiff_Call struct {
	*mock.Call
}

// LookupDiff is a helper method to define mock.On call
//   - buildID string
//   - diffType build.DiffType
func (_e *MockCache_Expecter) LookupDiff(buildID interface{}, diffType interface{}) *MockCache_LookupDiff_Call {
	return &MockCache_LookupDiff_Call{Call: _e.mock.On("LookupDiff", buildID, diffType)}
}

func (_c *MockCache_LookupDiff_Call) Run(run func(buildID string, diffType build.DiffType)) *MockCache_LookupDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 build.DiffType
		if args[1] != nil {
			arg1 = args[1].(build.DiffType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_LookupDiff_Call) Return(diff build.Diff, b bool) *MockCache_LookupDiff_Call {
	_c.Call.Return(diff, b)
	return _c
}

func (_c *MockCache_LookupDiff_Call) RunAndReturn(run func(buildID string, diffType build.DiffType) (build.Diff, bool)) *MockCache_LookupDiff_Call {
	_c.Call.Return(run)
	return _c
}

// LookupPinned provides a mock function for the type MockCache
func (_mock *MockCache) LookupPinned(ctx context.Context, buildID string) (template.Template, func(), bool) {
	ret := _mock.Called(ctx, buildID)

	if len(ret) == 0 {
		panic("no return value specified for LookupPinned")
	}

	var r0 template.Template
	var r1 func()
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (template.Template, func(), bool)); ok {
		return returnFunc(ctx, buildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) template.Template); ok {
		r0 = returnFunc(ctx, buildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(template.Template)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) func()); ok {
		r1 = returnFunc(ctx, buildID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) bool); ok {
		r2 = returnFunc(ctx, buildID)
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// MockCache_LookupPinned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupPinned'
type MockCache_LookupPinned_Call struct {
	*mock.Call
}

// LookupPinned is a helper method to define mock.On call
//   - ctx context.Context
//   - buildID string
func (_e *MockCache_Expecter) LookupPinned(ctx interface{}, buildID interface{}) *MockCache_LookupPinned_Call {
	return &MockCache_LookupPinned_Call{Call: _e.mock.On("LookupPinned", ctx, buildID)}
}

func (_c *MockCache_LookupPinned_Call) Run(run func(ctx context.Context, buildID string)) *MockCache_LookupPinned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_LookupPinned_Call) Return(template1 template.Template, fn func(), b bool) *MockCache_LookupPinned_Call {
	_c.Call.Return(template1, fn, b)
	return _c
}

func (_c *MockCache_LookupPinned_Call) RunAndReturn(run func(ctx context.Context, buildID string) (template.Template, func(), bool)) *MockCache_LookupPinned_Call {
	_c.Call.Return(run)
	return _c
}
