// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: e2b/webhooks/management/v1/webhook_management.proto

package management

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/e2b-dev/infra/packages/shared/pkg/grpc/contracts/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookDeliveryStatus int32

const (
	WebhookDeliveryStatus_WEBHOOK_DELIVERY_STATUS_UNSPECIFIED WebhookDeliveryStatus = 0
	WebhookDeliveryStatus_WEBHOOK_DELIVERY_STATUS_SUCCESS     WebhookDeliveryStatus = 1
	WebhookDeliveryStatus_WEBHOOK_DELIVERY_STATUS_FAILED      WebhookDeliveryStatus = 2
)

// Enum value maps for WebhookDeliveryStatus.
var (
	WebhookDeliveryStatus_name = map[int32]string{
		0: "WEBHOOK_DELIVERY_STATUS_UNSPECIFIED",
		1: "WEBHOOK_DELIVERY_STATUS_SUCCESS",
		2: "WEBHOOK_DELIVERY_STATUS_FAILED",
	}
	WebhookDeliveryStatus_value = map[string]int32{
		"WEBHOOK_DELIVERY_STATUS_UNSPECIFIED": 0,
		"WEBHOOK_DELIVERY_STATUS_SUCCESS":     1,
		"WEBHOOK_DELIVERY_STATUS_FAILED":      2,
	}
)

func (x WebhookDeliveryStatus) Enum() *WebhookDeliveryStatus {
	p := new(WebhookDeliveryStatus)
	*p = x
	return p
}

func (x WebhookDeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookDeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_e2b_webhooks_management_v1_webhook_management_proto_enumTypes[0].Descriptor()
}

func (WebhookDeliveryStatus) Type() protoreflect.EnumType {
	return &file_e2b_webhooks_management_v1_webhook_management_proto_enumTypes[0]
}

func (x WebhookDeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type WebhookDeliveryErrorClass int32

const (
	WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_UNSPECIFIED     WebhookDeliveryErrorClass = 0
	WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_HTTP_ERROR      WebhookDeliveryErrorClass = 1
	WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_DNS_ERROR       WebhookDeliveryErrorClass = 2
	WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_TIMEOUT         WebhookDeliveryErrorClass = 3
	WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_TRANSPORT_ERROR WebhookDeliveryErrorClass = 4
	WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_REQUEST_ERROR   WebhookDeliveryErrorClass = 5
	WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_SIGNATURE_ERROR WebhookDeliveryErrorClass = 6
	WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_CANCELED        WebhookDeliveryErrorClass = 7
)

// Enum value maps for WebhookDeliveryErrorClass.
var (
	WebhookDeliveryErrorClass_name = map[int32]string{
		0: "WEBHOOK_DELIVERY_ERROR_CLASS_UNSPECIFIED",
		1: "WEBHOOK_DELIVERY_ERROR_CLASS_HTTP_ERROR",
		2: "WEBHOOK_DELIVERY_ERROR_CLASS_DNS_ERROR",
		3: "WEBHOOK_DELIVERY_ERROR_CLASS_TIMEOUT",
		4: "WEBHOOK_DELIVERY_ERROR_CLASS_TRANSPORT_ERROR",
		5: "WEBHOOK_DELIVERY_ERROR_CLASS_REQUEST_ERROR",
		6: "WEBHOOK_DELIVERY_ERROR_CLASS_SIGNATURE_ERROR",
		7: "WEBHOOK_DELIVERY_ERROR_CLASS_CANCELED",
	}
	WebhookDeliveryErrorClass_value = map[string]int32{
		"WEBHOOK_DELIVERY_ERROR_CLASS_UNSPECIFIED":     0,
		"WEBHOOK_DELIVERY_ERROR_CLASS_HTTP_ERROR":      1,
		"WEBHOOK_DELIVERY_ERROR_CLASS_DNS_ERROR":       2,
		"WEBHOOK_DELIVERY_ERROR_CLASS_TIMEOUT":         3,
		"WEBHOOK_DELIVERY_ERROR_CLASS_TRANSPORT_ERROR": 4,
		"WEBHOOK_DELIVERY_ERROR_CLASS_REQUEST_ERROR":   5,
		"WEBHOOK_DELIVERY_ERROR_CLASS_SIGNATURE_ERROR": 6,
		"WEBHOOK_DELIVERY_ERROR_CLASS_CANCELED":        7,
	}
)

func (x WebhookDeliveryErrorClass) Enum() *WebhookDeliveryErrorClass {
	p := new(WebhookDeliveryErrorClass)
	*p = x
	return p
}

func (x WebhookDeliveryErrorClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookDeliveryErrorClass) Descriptor() protoreflect.EnumDescriptor {
	return file_e2b_webhooks_management_v1_webhook_management_proto_enumTypes[1].Descriptor()
}

func (WebhookDeliveryErrorClass) Type() protoreflect.EnumType {
	return &file_e2b_webhooks_management_v1_webhook_management_proto_enumTypes[1]
}

func (x WebhookDeliveryErrorClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Distinguishes RESOURCE_EXHAUSTED outcomes that map to different public API
// statuses without parsing a status description.
type WebhookManagementErrorReason int32

const (
	WebhookManagementErrorReason_WEBHOOK_MANAGEMENT_ERROR_REASON_UNSPECIFIED           WebhookManagementErrorReason = 0
	WebhookManagementErrorReason_WEBHOOK_MANAGEMENT_ERROR_REASON_WEBHOOK_LIMIT_REACHED WebhookManagementErrorReason = 1
)

// Enum value maps for WebhookManagementErrorReason.
var (
	WebhookManagementErrorReason_name = map[int32]string{
		0: "WEBHOOK_MANAGEMENT_ERROR_REASON_UNSPECIFIED",
		1: "WEBHOOK_MANAGEMENT_ERROR_REASON_WEBHOOK_LIMIT_REACHED",
	}
	WebhookManagementErrorReason_value = map[string]int32{
		"WEBHOOK_MANAGEMENT_ERROR_REASON_UNSPECIFIED":           0,
		"WEBHOOK_MANAGEMENT_ERROR_REASON_WEBHOOK_LIMIT_REACHED": 1,
	}
)

func (x WebhookManagementErrorReason) Enum() *WebhookManagementErrorReason {
	p := new(WebhookManagementErrorReason)
	*p = x
	return p
}

func (x WebhookManagementErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookManagementErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_e2b_webhooks_management_v1_webhook_management_proto_enumTypes[2].Descriptor()
}

func (WebhookManagementErrorReason) Type() protoreflect.EnumType {
	return &file_e2b_webhooks_management_v1_webhook_management_proto_enumTypes[2]
}

func (x WebhookManagementErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Webhook struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_WebhookId string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId"`
	xxx_hidden_TeamId    string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt"`
	xxx_hidden_Name      string                 `protobuf:"bytes,4,opt,name=name"`
	xxx_hidden_Url       string                 `protobuf:"bytes,5,opt,name=url"`
	xxx_hidden_Enabled   bool                   `protobuf:"varint,6,opt,name=enabled"`
	xxx_hidden_Events    []string               `protobuf:"bytes,7,rep,name=events"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Webhook) GetWebhookId() string {
	if x != nil {
		return x.xxx_hidden_WebhookId
	}
	return ""
}

func (x *Webhook) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *Webhook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Webhook) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Webhook) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *Webhook) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *Webhook) GetEvents() []string {
	if x != nil {
		return x.xxx_hidden_Events
	}
	return nil
}

func (x *Webhook) SetWebhookId(v string) {
	x.xxx_hidden_WebhookId = v
}

func (x *Webhook) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *Webhook) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Webhook) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Webhook) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

func (x *Webhook) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
}

func (x *Webhook) SetEvents(v []string) {
	x.xxx_hidden_Events = v
}

func (x *Webhook) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Webhook) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type Webhook_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	WebhookId string
	TeamId    string
	CreatedAt *timestamppb.Timestamp
	Name      string
	Url       string
	Enabled   bool
	Events    []string
}

func (b0 Webhook_builder) Build() *Webhook {
	m0 := &Webhook{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_WebhookId = b.WebhookId
	x.xxx_hidden_TeamId = b.TeamId
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Enabled = b.Enabled
	x.xxx_hidden_Events = b.Events
	return m0
}

type CreateWebhookRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamId          string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId"`
	xxx_hidden_ClusterId       *string                `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId"`
	xxx_hidden_Name            string                 `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_Url             string                 `protobuf:"bytes,4,opt,name=url"`
	xxx_hidden_Events          []string               `protobuf:"bytes,5,rep,name=events"`
	xxx_hidden_Enabled         bool                   `protobuf:"varint,6,opt,name=enabled"`
	xxx_hidden_SignatureSecret string                 `protobuf:"bytes,7,opt,name=signature_secret,json=signatureSecret"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CreateWebhookRequest) Reset() {
	*x = CreateWebhookRequest{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookRequest) ProtoMessage() {}

func (x *CreateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateWebhookRequest) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *CreateWebhookRequest) GetClusterId() string {
	if x != nil {
		if x.xxx_hidden_ClusterId != nil {
			return *x.xxx_hidden_ClusterId
		}
		return ""
	}
	return ""
}

func (x *CreateWebhookRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *CreateWebhookRequest) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *CreateWebhookRequest) GetEvents() []string {
	if x != nil {
		return x.xxx_hidden_Events
	}
	return nil
}

func (x *CreateWebhookRequest) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *CreateWebhookRequest) GetSignatureSecret() string {
	if x != nil {
		return x.xxx_hidden_SignatureSecret
	}
	return ""
}

func (x *CreateWebhookRequest) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *CreateWebhookRequest) SetClusterId(v string) {
	x.xxx_hidden_ClusterId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *CreateWebhookRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *CreateWebhookRequest) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

func (x *CreateWebhookRequest) SetEvents(v []string) {
	x.xxx_hidden_Events = v
}

func (x *CreateWebhookRequest) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *CreateWebhookRequest) SetSignatureSecret(v string) {
	x.xxx_hidden_SignatureSecret = v
}

func (x *CreateWebhookRequest) HasClusterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateWebhookRequest) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CreateWebhookRequest) ClearClusterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClusterId = nil
}

func (x *CreateWebhookRequest) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Enabled = false
}

type CreateWebhookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamId string
	// Omission selects the local cluster.
	ClusterId *string
	Name      string
	Url       string
	// The allowed event types are validated by the server against the shared
	// events package, the single source of truth for sandbox event types.
	Events []string
	// Omission defaults to true.
	Enabled         *bool
	SignatureSecret string
}

func (b0 CreateWebhookRequest_builder) Build() *CreateWebhookRequest {
	m0 := &CreateWebhookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamId = b.TeamId
	if b.ClusterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_ClusterId = b.ClusterId
	}
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Events = b.Events
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	x.xxx_hidden_SignatureSecret = b.SignatureSecret
	return m0
}

type CreateWebhookResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Webhook *Webhook               `protobuf:"bytes,1,opt,name=webhook"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateWebhookResponse) Reset() {
	*x = CreateWebhookResponse{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookResponse) ProtoMessage() {}

func (x *CreateWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.xxx_hidden_Webhook
	}
	return nil
}

func (x *CreateWebhookResponse) SetWebhook(v *Webhook) {
	x.xxx_hidden_Webhook = v
}

func (x *CreateWebhookResponse) HasWebhook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Webhook != nil
}

func (x *CreateWebhookResponse) ClearWebhook() {
	x.xxx_hidden_Webhook = nil
}

type CreateWebhookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Webhook *Webhook
}

func (b0 CreateWebhookResponse_builder) Build() *CreateWebhookResponse {
	m0 := &CreateWebhookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Webhook = b.Webhook
	return m0
}

type ListWebhooksRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamId string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListWebhooksRequest) Reset() {
	*x = ListWebhooksRequest{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksRequest) ProtoMessage() {}

func (x *ListWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListWebhooksRequest) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *ListWebhooksRequest) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

type ListWebhooksRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamId string
}

func (b0 ListWebhooksRequest_builder) Build() *ListWebhooksRequest {
	m0 := &ListWebhooksRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamId = b.TeamId
	return m0
}

type ListWebhooksResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Webhooks *[]*Webhook            `protobuf:"bytes,1,rep,name=webhooks"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListWebhooksResponse) Reset() {
	*x = ListWebhooksResponse{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksResponse) ProtoMessage() {}

func (x *ListWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListWebhooksResponse) GetWebhooks() []*Webhook {
	if x != nil {
		if x.xxx_hidden_Webhooks != nil {
			return *x.xxx_hidden_Webhooks
		}
	}
	return nil
}

func (x *ListWebhooksResponse) SetWebhooks(v []*Webhook) {
	x.xxx_hidden_Webhooks = &v
}

type ListWebhooksResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Webhooks []*Webhook
}

func (b0 ListWebhooksResponse_builder) Build() *ListWebhooksResponse {
	m0 := &ListWebhooksResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Webhooks = &b.Webhooks
	return m0
}

type GetWebhookRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamId    string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId"`
	xxx_hidden_WebhookId string                 `protobuf:"bytes,2,opt,name=webhook_id,json=webhookId"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetWebhookRequest) Reset() {
	*x = GetWebhookRequest{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookRequest) ProtoMessage() {}

func (x *GetWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetWebhookRequest) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *GetWebhookRequest) GetWebhookId() string {
	if x != nil {
		return x.xxx_hidden_WebhookId
	}
	return ""
}

func (x *GetWebhookRequest) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *GetWebhookRequest) SetWebhookId(v string) {
	x.xxx_hidden_WebhookId = v
}

type GetWebhookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamId    string
	WebhookId string
}

func (b0 GetWebhookRequest_builder) Build() *GetWebhookRequest {
	m0 := &GetWebhookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamId = b.TeamId
	x.xxx_hidden_WebhookId = b.WebhookId
	return m0
}

type GetWebhookResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Webhook *Webhook               `protobuf:"bytes,1,opt,name=webhook"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetWebhookResponse) Reset() {
	*x = GetWebhookResponse{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookResponse) ProtoMessage() {}

func (x *GetWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.xxx_hidden_Webhook
	}
	return nil
}

func (x *GetWebhookResponse) SetWebhook(v *Webhook) {
	x.xxx_hidden_Webhook = v
}

func (x *GetWebhookResponse) HasWebhook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Webhook != nil
}

func (x *GetWebhookResponse) ClearWebhook() {
	x.xxx_hidden_Webhook = nil
}

type GetWebhookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Webhook *Webhook
}

func (b0 GetWebhookResponse_builder) Build() *GetWebhookResponse {
	m0 := &GetWebhookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Webhook = b.Webhook
	return m0
}

// Preserves the distinction between an omitted update and an explicitly empty
// list. A present empty list is rejected by webhook validation.
type WebhookEventsUpdate struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values []string               `protobuf:"bytes,1,rep,name=values"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebhookEventsUpdate) Reset() {
	*x = WebhookEventsUpdate{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEventsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEventsUpdate) ProtoMessage() {}

func (x *WebhookEventsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebhookEventsUpdate) GetValues() []string {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *WebhookEventsUpdate) SetValues(v []string) {
	x.xxx_hidden_Values = v
}

type WebhookEventsUpdate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The allowed event types are validated by the server against the shared
	// events package, the single source of truth for sandbox event types.
	Values []string
}

func (b0 WebhookEventsUpdate_builder) Build() *WebhookEventsUpdate {
	m0 := &WebhookEventsUpdate{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = b.Values
	return m0
}

type UpdateWebhookRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamId          string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId"`
	xxx_hidden_ClusterId       *string                `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId"`
	xxx_hidden_WebhookId       string                 `protobuf:"bytes,3,opt,name=webhook_id,json=webhookId"`
	xxx_hidden_Name            *string                `protobuf:"bytes,4,opt,name=name"`
	xxx_hidden_Url             *string                `protobuf:"bytes,5,opt,name=url"`
	xxx_hidden_Events          *WebhookEventsUpdate   `protobuf:"bytes,6,opt,name=events"`
	xxx_hidden_Enabled         bool                   `protobuf:"varint,7,opt,name=enabled"`
	xxx_hidden_SignatureSecret *string                `protobuf:"bytes,8,opt,name=signature_secret,json=signatureSecret"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateWebhookRequest) Reset() {
	*x = UpdateWebhookRequest{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookRequest) ProtoMessage() {}

func (x *UpdateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateWebhookRequest) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *UpdateWebhookRequest) GetClusterId() string {
	if x != nil {
		if x.xxx_hidden_ClusterId != nil {
			return *x.xxx_hidden_ClusterId
		}
		return ""
	}
	return ""
}

func (x *UpdateWebhookRequest) GetWebhookId() string {
	if x != nil {
		return x.xxx_hidden_WebhookId
	}
	return ""
}

func (x *UpdateWebhookRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UpdateWebhookRequest) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *UpdateWebhookRequest) GetEvents() *WebhookEventsUpdate {
	if x != nil {
		return x.xxx_hidden_Events
	}
	return nil
}

func (x *UpdateWebhookRequest) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *UpdateWebhookRequest) GetSignatureSecret() string {
	if x != nil {
		if x.xxx_hidden_SignatureSecret != nil {
			return *x.xxx_hidden_SignatureSecret
		}
		return ""
	}
	return ""
}

func (x *UpdateWebhookRequest) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *UpdateWebhookRequest) SetClusterId(v string) {
	x.xxx_hidden_ClusterId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *UpdateWebhookRequest) SetWebhookId(v string) {
	x.xxx_hidden_WebhookId = v
}

func (x *UpdateWebhookRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *UpdateWebhookRequest) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *UpdateWebhookRequest) SetEvents(v *WebhookEventsUpdate) {
	x.xxx_hidden_Events = v
}

func (x *UpdateWebhookRequest) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *UpdateWebhookRequest) SetSignatureSecret(v string) {
	x.xxx_hidden_SignatureSecret = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *UpdateWebhookRequest) HasClusterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateWebhookRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateWebhookRequest) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UpdateWebhookRequest) HasEvents() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Events != nil
}

func (x *UpdateWebhookRequest) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *UpdateWebhookRequest) HasSignatureSecret() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *UpdateWebhookRequest) ClearClusterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClusterId = nil
}

func (x *UpdateWebhookRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = nil
}

func (x *UpdateWebhookRequest) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Url = nil
}

func (x *UpdateWebhookRequest) ClearEvents() {
	x.xxx_hidden_Events = nil
}

func (x *UpdateWebhookRequest) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Enabled = false
}

func (x *UpdateWebhookRequest) ClearSignatureSecret() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_SignatureSecret = nil
}

type UpdateWebhookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamId string
	// Omission selects the local cluster.
	ClusterId *string
	WebhookId string
	Name      *string
	Url       *string
	// The rule sits here rather than on the wrapper's repeated field so a
	// violation names the field the caller sent, not the wrapper that exists to
	// give that field presence.
	Events          *WebhookEventsUpdate
	Enabled         *bool
	SignatureSecret *string
}

func (b0 UpdateWebhookRequest_builder) Build() *UpdateWebhookRequest {
	m0 := &UpdateWebhookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamId = b.TeamId
	if b.ClusterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_ClusterId = b.ClusterId
	}
	x.xxx_hidden_WebhookId = b.WebhookId
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Name = b.Name
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Url = b.Url
	}
	x.xxx_hidden_Events = b.Events
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.SignatureSecret != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_SignatureSecret = b.SignatureSecret
	}
	return m0
}

type UpdateWebhookResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Webhook *Webhook               `protobuf:"bytes,1,opt,name=webhook"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateWebhookResponse) Reset() {
	*x = UpdateWebhookResponse{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookResponse) ProtoMessage() {}

func (x *UpdateWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.xxx_hidden_Webhook
	}
	return nil
}

func (x *UpdateWebhookResponse) SetWebhook(v *Webhook) {
	x.xxx_hidden_Webhook = v
}

func (x *UpdateWebhookResponse) HasWebhook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Webhook != nil
}

func (x *UpdateWebhookResponse) ClearWebhook() {
	x.xxx_hidden_Webhook = nil
}

type UpdateWebhookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Webhook *Webhook
}

func (b0 UpdateWebhookResponse_builder) Build() *UpdateWebhookResponse {
	m0 := &UpdateWebhookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Webhook = b.Webhook
	return m0
}

type DeleteWebhookRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamId      string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId"`
	xxx_hidden_ClusterId   *string                `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId"`
	xxx_hidden_WebhookId   string                 `protobuf:"bytes,3,opt,name=webhook_id,json=webhookId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteWebhookRequest) Reset() {
	*x = DeleteWebhookRequest{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookRequest) ProtoMessage() {}

func (x *DeleteWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteWebhookRequest) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *DeleteWebhookRequest) GetClusterId() string {
	if x != nil {
		if x.xxx_hidden_ClusterId != nil {
			return *x.xxx_hidden_ClusterId
		}
		return ""
	}
	return ""
}

func (x *DeleteWebhookRequest) GetWebhookId() string {
	if x != nil {
		return x.xxx_hidden_WebhookId
	}
	return ""
}

func (x *DeleteWebhookRequest) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *DeleteWebhookRequest) SetClusterId(v string) {
	x.xxx_hidden_ClusterId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *DeleteWebhookRequest) SetWebhookId(v string) {
	x.xxx_hidden_WebhookId = v
}

func (x *DeleteWebhookRequest) HasClusterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteWebhookRequest) ClearClusterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClusterId = nil
}

type DeleteWebhookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamId string
	// Omission selects the local cluster.
	ClusterId *string
	WebhookId string
}

func (b0 DeleteWebhookRequest_builder) Build() *DeleteWebhookRequest {
	m0 := &DeleteWebhookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamId = b.TeamId
	if b.ClusterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ClusterId = b.ClusterId
	}
	x.xxx_hidden_WebhookId = b.WebhookId
	return m0
}

type DeleteWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookResponse) Reset() {
	*x = DeleteWebhookResponse{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookResponse) ProtoMessage() {}

func (x *DeleteWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteWebhookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteWebhookResponse_builder) Build() *DeleteWebhookResponse {
	m0 := &DeleteWebhookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListWebhookDeliveriesRequest struct {
	state                       protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_TeamId           string                  `protobuf:"bytes,1,opt,name=team_id,json=teamId"`
	xxx_hidden_ClusterId        *string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId"`
	xxx_hidden_WebhookId        string                  `protobuf:"bytes,3,opt,name=webhook_id,json=webhookId"`
	xxx_hidden_Cursor           string                  `protobuf:"bytes,4,opt,name=cursor"`
	xxx_hidden_Limit            int32                   `protobuf:"varint,5,opt,name=limit"`
	xxx_hidden_OrderAsc         bool                    `protobuf:"varint,6,opt,name=order_asc,json=orderAsc"`
	xxx_hidden_Start            *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=start"`
	xxx_hidden_End              *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=end"`
	xxx_hidden_DeliveryStatuses []WebhookDeliveryStatus `protobuf:"varint,9,rep,packed,name=delivery_statuses,json=deliveryStatuses,enum=e2b.webhooks.management.v1.WebhookDeliveryStatus"`
	xxx_hidden_EventTypes       []string                `protobuf:"bytes,10,rep,name=event_types,json=eventTypes"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ListWebhookDeliveriesRequest) Reset() {
	*x = ListWebhookDeliveriesRequest{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookDeliveriesRequest) ProtoMessage() {}

func (x *ListWebhookDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListWebhookDeliveriesRequest) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *ListWebhookDeliveriesRequest) GetClusterId() string {
	if x != nil {
		if x.xxx_hidden_ClusterId != nil {
			return *x.xxx_hidden_ClusterId
		}
		return ""
	}
	return ""
}

func (x *ListWebhookDeliveriesRequest) GetWebhookId() string {
	if x != nil {
		return x.xxx_hidden_WebhookId
	}
	return ""
}

func (x *ListWebhookDeliveriesRequest) GetCursor() string {
	if x != nil {
		return x.xxx_hidden_Cursor
	}
	return ""
}

func (x *ListWebhookDeliveriesRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListWebhookDeliveriesRequest) GetOrderAsc() bool {
	if x != nil {
		return x.xxx_hidden_OrderAsc
	}
	return false
}

func (x *ListWebhookDeliveriesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *ListWebhookDeliveriesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *ListWebhookDeliveriesRequest) GetDeliveryStatuses() []WebhookDeliveryStatus {
	if x != nil {
		return x.xxx_hidden_DeliveryStatuses
	}
	return nil
}

func (x *ListWebhookDeliveriesRequest) GetEventTypes() []string {
	if x != nil {
		return x.xxx_hidden_EventTypes
	}
	return nil
}

func (x *ListWebhookDeliveriesRequest) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *ListWebhookDeliveriesRequest) SetClusterId(v string) {
	x.xxx_hidden_ClusterId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *ListWebhookDeliveriesRequest) SetWebhookId(v string) {
	x.xxx_hidden_WebhookId = v
}

func (x *ListWebhookDeliveriesRequest) SetCursor(v string) {
	x.xxx_hidden_Cursor = v
}

func (x *ListWebhookDeliveriesRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *ListWebhookDeliveriesRequest) SetOrderAsc(v bool) {
	x.xxx_hidden_OrderAsc = v
}

func (x *ListWebhookDeliveriesRequest) SetStart(v *timestamppb.Timestamp) {
	x.xxx_hidden_Start = v
}

func (x *ListWebhookDeliveriesRequest) SetEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_End = v
}

func (x *ListWebhookDeliveriesRequest) SetDeliveryStatuses(v []WebhookDeliveryStatus) {
	x.xxx_hidden_DeliveryStatuses = v
}

func (x *ListWebhookDeliveriesRequest) SetEventTypes(v []string) {
	x.xxx_hidden_EventTypes = v
}

func (x *ListWebhookDeliveriesRequest) HasClusterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListWebhookDeliveriesRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ListWebhookDeliveriesRequest) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *ListWebhookDeliveriesRequest) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *ListWebhookDeliveriesRequest) ClearClusterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClusterId = nil
}

func (x *ListWebhookDeliveriesRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Limit = 0
}

func (x *ListWebhookDeliveriesRequest) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *ListWebhookDeliveriesRequest) ClearEnd() {
	x.xxx_hidden_End = nil
}

type ListWebhookDeliveriesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamId string
	// Omission selects the local cluster.
	ClusterId *string
	WebhookId string
	// Opaque cursor returned by the previous page. Empty selects the first page.
	Cursor string
	// Omission defaults to 25. Values must be between 1 and 100.
	Limit    *int32
	OrderAsc bool
	// The range is start-inclusive and end-exclusive. Both fields must be set
	// together; omitting both leaves the range unbounded.
	Start            *timestamppb.Timestamp
	End              *timestamppb.Timestamp
	DeliveryStatuses []WebhookDeliveryStatus
	EventTypes       []string
}

func (b0 ListWebhookDeliveriesRequest_builder) Build() *ListWebhookDeliveriesRequest {
	m0 := &ListWebhookDeliveriesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamId = b.TeamId
	if b.ClusterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_ClusterId = b.ClusterId
	}
	x.xxx_hidden_WebhookId = b.WebhookId
	x.xxx_hidden_Cursor = b.Cursor
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_Limit = *b.Limit
	}
	x.xxx_hidden_OrderAsc = b.OrderAsc
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	x.xxx_hidden_DeliveryStatuses = b.DeliveryStatuses
	x.xxx_hidden_EventTypes = b.EventTypes
	return m0
}

type ListWebhookDeliveriesResponse struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Groups      *[]*WebhookDeliveryGroup `protobuf:"bytes,1,rep,name=groups"`
	xxx_hidden_NextCursor  *string                  `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListWebhookDeliveriesResponse) Reset() {
	*x = ListWebhookDeliveriesResponse{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookDeliveriesResponse) ProtoMessage() {}

func (x *ListWebhookDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListWebhookDeliveriesResponse) GetGroups() []*WebhookDeliveryGroup {
	if x != nil {
		if x.xxx_hidden_Groups != nil {
			return *x.xxx_hidden_Groups
		}
	}
	return nil
}

func (x *ListWebhookDeliveriesResponse) GetNextCursor() string {
	if x != nil {
		if x.xxx_hidden_NextCursor != nil {
			return *x.xxx_hidden_NextCursor
		}
		return ""
	}
	return ""
}

func (x *ListWebhookDeliveriesResponse) SetGroups(v []*WebhookDeliveryGroup) {
	x.xxx_hidden_Groups = &v
}

func (x *ListWebhookDeliveriesResponse) SetNextCursor(v string) {
	x.xxx_hidden_NextCursor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ListWebhookDeliveriesResponse) HasNextCursor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListWebhookDeliveriesResponse) ClearNextCursor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextCursor = nil
}

type ListWebhookDeliveriesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Pagination is applied to attempts before they are grouped by event.
	Groups []*WebhookDeliveryGroup
	// Omitted on the last page.
	NextCursor *string
}

func (b0 ListWebhookDeliveriesResponse_builder) Build() *ListWebhookDeliveriesResponse {
	m0 := &ListWebhookDeliveriesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Groups = &b.Groups
	if b.NextCursor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NextCursor = b.NextCursor
	}
	return m0
}

type WebhookDeliveryGroup struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId"`
	xxx_hidden_EventType string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType"`
	xxx_hidden_SandboxId string                 `protobuf:"bytes,3,opt,name=sandbox_id,json=sandboxId"`
	xxx_hidden_Attempts  *[]*WebhookDelivery    `protobuf:"bytes,4,rep,name=attempts"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WebhookDeliveryGroup) Reset() {
	*x = WebhookDeliveryGroup{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDeliveryGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDeliveryGroup) ProtoMessage() {}

func (x *WebhookDeliveryGroup) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebhookDeliveryGroup) GetEventId() string {
	if x != nil {
		return x.xxx_hidden_EventId
	}
	return ""
}

func (x *WebhookDeliveryGroup) GetEventType() string {
	if x != nil {
		return x.xxx_hidden_EventType
	}
	return ""
}

func (x *WebhookDeliveryGroup) GetSandboxId() string {
	if x != nil {
		return x.xxx_hidden_SandboxId
	}
	return ""
}

func (x *WebhookDeliveryGroup) GetAttempts() []*WebhookDelivery {
	if x != nil {
		if x.xxx_hidden_Attempts != nil {
			return *x.xxx_hidden_Attempts
		}
	}
	return nil
}

func (x *WebhookDeliveryGroup) SetEventId(v string) {
	x.xxx_hidden_EventId = v
}

func (x *WebhookDeliveryGroup) SetEventType(v string) {
	x.xxx_hidden_EventType = v
}

func (x *WebhookDeliveryGroup) SetSandboxId(v string) {
	x.xxx_hidden_SandboxId = v
}

func (x *WebhookDeliveryGroup) SetAttempts(v []*WebhookDelivery) {
	x.xxx_hidden_Attempts = &v
}

type WebhookDeliveryGroup_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventId   string
	EventType string
	SandboxId string
	Attempts  []*WebhookDelivery
}

func (b0 WebhookDeliveryGroup_builder) Build() *WebhookDeliveryGroup {
	m0 := &WebhookDeliveryGroup{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventId = b.EventId
	x.xxx_hidden_EventType = b.EventType
	x.xxx_hidden_SandboxId = b.SandboxId
	x.xxx_hidden_Attempts = &b.Attempts
	return m0
}

type WebhookDelivery struct {
	state                             protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_DeliveryId             string                    `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId"`
	xxx_hidden_TeamId                 string                    `protobuf:"bytes,2,opt,name=team_id,json=teamId"`
	xxx_hidden_WebhookId              string                    `protobuf:"bytes,3,opt,name=webhook_id,json=webhookId"`
	xxx_hidden_EventId                string                    `protobuf:"bytes,4,opt,name=event_id,json=eventId"`
	xxx_hidden_SandboxId              string                    `protobuf:"bytes,5,opt,name=sandbox_id,json=sandboxId"`
	xxx_hidden_EventType              string                    `protobuf:"bytes,6,opt,name=event_type,json=eventType"`
	xxx_hidden_Status                 WebhookDeliveryStatus     `protobuf:"varint,7,opt,name=status,enum=e2b.webhooks.management.v1.WebhookDeliveryStatus"`
	xxx_hidden_DurationMs             int32                     `protobuf:"varint,8,opt,name=duration_ms,json=durationMs"`
	xxx_hidden_RequestBody            string                    `protobuf:"bytes,9,opt,name=request_body,json=requestBody"`
	xxx_hidden_RequestHeaders         string                    `protobuf:"bytes,10,opt,name=request_headers,json=requestHeaders"`
	xxx_hidden_RequestUrl             string                    `protobuf:"bytes,11,opt,name=request_url,json=requestUrl"`
	xxx_hidden_ResponseBody           *string                   `protobuf:"bytes,12,opt,name=response_body,json=responseBody"`
	xxx_hidden_ResponseHeaders        *string                   `protobuf:"bytes,13,opt,name=response_headers,json=responseHeaders"`
	xxx_hidden_ResponseHttpStatusCode int32                     `protobuf:"varint,14,opt,name=response_http_status_code,json=responseHttpStatusCode"`
	xxx_hidden_ErrorClass             WebhookDeliveryErrorClass `protobuf:"varint,15,opt,name=error_class,json=errorClass,enum=e2b.webhooks.management.v1.WebhookDeliveryErrorClass"`
	xxx_hidden_ErrorMessage           *string                   `protobuf:"bytes,16,opt,name=error_message,json=errorMessage"`
	xxx_hidden_Timestamp              *timestamppb.Timestamp    `protobuf:"bytes,17,opt,name=timestamp"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *WebhookDelivery) Reset() {
	*x = WebhookDelivery{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDelivery) ProtoMessage() {}

func (x *WebhookDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebhookDelivery) GetDeliveryId() string {
	if x != nil {
		return x.xxx_hidden_DeliveryId
	}
	return ""
}

func (x *WebhookDelivery) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *WebhookDelivery) GetWebhookId() string {
	if x != nil {
		return x.xxx_hidden_WebhookId
	}
	return ""
}

func (x *WebhookDelivery) GetEventId() string {
	if x != nil {
		return x.xxx_hidden_EventId
	}
	return ""
}

func (x *WebhookDelivery) GetSandboxId() string {
	if x != nil {
		return x.xxx_hidden_SandboxId
	}
	return ""
}

func (x *WebhookDelivery) GetEventType() string {
	if x != nil {
		return x.xxx_hidden_EventType
	}
	return ""
}

func (x *WebhookDelivery) GetStatus() WebhookDeliveryStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return WebhookDeliveryStatus_WEBHOOK_DELIVERY_STATUS_UNSPECIFIED
}

func (x *WebhookDelivery) GetDurationMs() int32 {
	if x != nil {
		return x.xxx_hidden_DurationMs
	}
	return 0
}

func (x *WebhookDelivery) GetRequestBody() string {
	if x != nil {
		return x.xxx_hidden_RequestBody
	}
	return ""
}

func (x *WebhookDelivery) GetRequestHeaders() string {
	if x != nil {
		return x.xxx_hidden_RequestHeaders
	}
	return ""
}

func (x *WebhookDelivery) GetRequestUrl() string {
	if x != nil {
		return x.xxx_hidden_RequestUrl
	}
	return ""
}

func (x *WebhookDelivery) GetResponseBody() string {
	if x != nil {
		if x.xxx_hidden_ResponseBody != nil {
			return *x.xxx_hidden_ResponseBody
		}
		return ""
	}
	return ""
}

func (x *WebhookDelivery) GetResponseHeaders() string {
	if x != nil {
		if x.xxx_hidden_ResponseHeaders != nil {
			return *x.xxx_hidden_ResponseHeaders
		}
		return ""
	}
	return ""
}

func (x *WebhookDelivery) GetResponseHttpStatusCode() int32 {
	if x != nil {
		return x.xxx_hidden_ResponseHttpStatusCode
	}
	return 0
}

func (x *WebhookDelivery) GetErrorClass() WebhookDeliveryErrorClass {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 14) {
			return x.xxx_hidden_ErrorClass
		}
	}
	return WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_UNSPECIFIED
}

func (x *WebhookDelivery) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *WebhookDelivery) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *WebhookDelivery) SetDeliveryId(v string) {
	x.xxx_hidden_DeliveryId = v
}

func (x *WebhookDelivery) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *WebhookDelivery) SetWebhookId(v string) {
	x.xxx_hidden_WebhookId = v
}

func (x *WebhookDelivery) SetEventId(v string) {
	x.xxx_hidden_EventId = v
}

func (x *WebhookDelivery) SetSandboxId(v string) {
	x.xxx_hidden_SandboxId = v
}

func (x *WebhookDelivery) SetEventType(v string) {
	x.xxx_hidden_EventType = v
}

func (x *WebhookDelivery) SetStatus(v WebhookDeliveryStatus) {
	x.xxx_hidden_Status = v
}

func (x *WebhookDelivery) SetDurationMs(v int32) {
	x.xxx_hidden_DurationMs = v
}

func (x *WebhookDelivery) SetRequestBody(v string) {
	x.xxx_hidden_RequestBody = v
}

func (x *WebhookDelivery) SetRequestHeaders(v string) {
	x.xxx_hidden_RequestHeaders = v
}

func (x *WebhookDelivery) SetRequestUrl(v string) {
	x.xxx_hidden_RequestUrl = v
}

func (x *WebhookDelivery) SetResponseBody(v string) {
	x.xxx_hidden_ResponseBody = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 17)
}

func (x *WebhookDelivery) SetResponseHeaders(v string) {
	x.xxx_hidden_ResponseHeaders = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 17)
}

func (x *WebhookDelivery) SetResponseHttpStatusCode(v int32) {
	x.xxx_hidden_ResponseHttpStatusCode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 17)
}

func (x *WebhookDelivery) SetErrorClass(v WebhookDeliveryErrorClass) {
	x.xxx_hidden_ErrorClass = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 17)
}

func (x *WebhookDelivery) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 17)
}

func (x *WebhookDelivery) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *WebhookDelivery) HasResponseBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *WebhookDelivery) HasResponseHeaders() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *WebhookDelivery) HasResponseHttpStatusCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *WebhookDelivery) HasErrorClass() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *WebhookDelivery) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *WebhookDelivery) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *WebhookDelivery) ClearResponseBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_ResponseBody = nil
}

func (x *WebhookDelivery) ClearResponseHeaders() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_ResponseHeaders = nil
}

func (x *WebhookDelivery) ClearResponseHttpStatusCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_ResponseHttpStatusCode = 0
}

func (x *WebhookDelivery) ClearErrorClass() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_ErrorClass = WebhookDeliveryErrorClass_WEBHOOK_DELIVERY_ERROR_CLASS_UNSPECIFIED
}

func (x *WebhookDelivery) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_ErrorMessage = nil
}

func (x *WebhookDelivery) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

type WebhookDelivery_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeliveryId             string
	TeamId                 string
	WebhookId              string
	EventId                string
	SandboxId              string
	EventType              string
	Status                 WebhookDeliveryStatus
	DurationMs             int32
	RequestBody            string
	RequestHeaders         string
	RequestUrl             string
	ResponseBody           *string
	ResponseHeaders        *string
	ResponseHttpStatusCode *int32
	ErrorClass             *WebhookDeliveryErrorClass
	ErrorMessage           *string
	Timestamp              *timestamppb.Timestamp
}

func (b0 WebhookDelivery_builder) Build() *WebhookDelivery {
	m0 := &WebhookDelivery{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DeliveryId = b.DeliveryId
	x.xxx_hidden_TeamId = b.TeamId
	x.xxx_hidden_WebhookId = b.WebhookId
	x.xxx_hidden_EventId = b.EventId
	x.xxx_hidden_SandboxId = b.SandboxId
	x.xxx_hidden_EventType = b.EventType
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_DurationMs = b.DurationMs
	x.xxx_hidden_RequestBody = b.RequestBody
	x.xxx_hidden_RequestHeaders = b.RequestHeaders
	x.xxx_hidden_RequestUrl = b.RequestUrl
	if b.ResponseBody != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 17)
		x.xxx_hidden_ResponseBody = b.ResponseBody
	}
	if b.ResponseHeaders != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 17)
		x.xxx_hidden_ResponseHeaders = b.ResponseHeaders
	}
	if b.ResponseHttpStatusCode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 17)
		x.xxx_hidden_ResponseHttpStatusCode = *b.ResponseHttpStatusCode
	}
	if b.ErrorClass != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 17)
		x.xxx_hidden_ErrorClass = *b.ErrorClass
	}
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 17)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	x.xxx_hidden_Timestamp = b.Timestamp
	return m0
}

type GetWebhookDeliveryStatsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamId      string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId"`
	xxx_hidden_ClusterId   *string                `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId"`
	xxx_hidden_WebhookId   string                 `protobuf:"bytes,3,opt,name=webhook_id,json=webhookId"`
	xxx_hidden_Start       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start"`
	xxx_hidden_End         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetWebhookDeliveryStatsRequest) Reset() {
	*x = GetWebhookDeliveryStatsRequest{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookDeliveryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookDeliveryStatsRequest) ProtoMessage() {}

func (x *GetWebhookDeliveryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetWebhookDeliveryStatsRequest) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *GetWebhookDeliveryStatsRequest) GetClusterId() string {
	if x != nil {
		if x.xxx_hidden_ClusterId != nil {
			return *x.xxx_hidden_ClusterId
		}
		return ""
	}
	return ""
}

func (x *GetWebhookDeliveryStatsRequest) GetWebhookId() string {
	if x != nil {
		return x.xxx_hidden_WebhookId
	}
	return ""
}

func (x *GetWebhookDeliveryStatsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *GetWebhookDeliveryStatsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *GetWebhookDeliveryStatsRequest) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *GetWebhookDeliveryStatsRequest) SetClusterId(v string) {
	x.xxx_hidden_ClusterId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *GetWebhookDeliveryStatsRequest) SetWebhookId(v string) {
	x.xxx_hidden_WebhookId = v
}

func (x *GetWebhookDeliveryStatsRequest) SetStart(v *timestamppb.Timestamp) {
	x.xxx_hidden_Start = v
}

func (x *GetWebhookDeliveryStatsRequest) SetEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_End = v
}

func (x *GetWebhookDeliveryStatsRequest) HasClusterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetWebhookDeliveryStatsRequest) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *GetWebhookDeliveryStatsRequest) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *GetWebhookDeliveryStatsRequest) ClearClusterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClusterId = nil
}

func (x *GetWebhookDeliveryStatsRequest) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *GetWebhookDeliveryStatsRequest) ClearEnd() {
	x.xxx_hidden_End = nil
}

type GetWebhookDeliveryStatsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamId string
	// Omission selects the local cluster.
	ClusterId *string
	WebhookId string
	// Omission defaults to 24 hours before end.
	Start *timestamppb.Timestamp
	// Omission defaults to the server's current time.
	End *timestamppb.Timestamp
}

func (b0 GetWebhookDeliveryStatsRequest_builder) Build() *GetWebhookDeliveryStatsRequest {
	m0 := &GetWebhookDeliveryStatsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamId = b.TeamId
	if b.ClusterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_ClusterId = b.ClusterId
	}
	x.xxx_hidden_WebhookId = b.WebhookId
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	return m0
}

type GetWebhookDeliveryStatsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stats *WebhookDeliveryStats  `protobuf:"bytes,1,opt,name=stats"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetWebhookDeliveryStatsResponse) Reset() {
	*x = GetWebhookDeliveryStatsResponse{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookDeliveryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookDeliveryStatsResponse) ProtoMessage() {}

func (x *GetWebhookDeliveryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetWebhookDeliveryStatsResponse) GetStats() *WebhookDeliveryStats {
	if x != nil {
		return x.xxx_hidden_Stats
	}
	return nil
}

func (x *GetWebhookDeliveryStatsResponse) SetStats(v *WebhookDeliveryStats) {
	x.xxx_hidden_Stats = v
}

func (x *GetWebhookDeliveryStatsResponse) HasStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stats != nil
}

func (x *GetWebhookDeliveryStatsResponse) ClearStats() {
	x.xxx_hidden_Stats = nil
}

type GetWebhookDeliveryStatsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Stats *WebhookDeliveryStats
}

func (b0 GetWebhookDeliveryStatsResponse_builder) Build() *GetWebhookDeliveryStatsResponse {
	m0 := &GetWebhookDeliveryStatsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stats = b.Stats
	return m0
}

type WebhookDeliveryStats struct {
	state                 protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Buckets    *[]*WebhookDeliveryStatsBucket `protobuf:"bytes,1,rep,name=buckets"`
	xxx_hidden_Total      int64                          `protobuf:"varint,2,opt,name=total"`
	xxx_hidden_Failed     int64                          `protobuf:"varint,3,opt,name=failed"`
	xxx_hidden_DurationMs *WebhookDeliveryDurationStats  `protobuf:"bytes,4,opt,name=duration_ms,json=durationMs"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WebhookDeliveryStats) Reset() {
	*x = WebhookDeliveryStats{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDeliveryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDeliveryStats) ProtoMessage() {}

func (x *WebhookDeliveryStats) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebhookDeliveryStats) GetBuckets() []*WebhookDeliveryStatsBucket {
	if x != nil {
		if x.xxx_hidden_Buckets != nil {
			return *x.xxx_hidden_Buckets
		}
	}
	return nil
}

func (x *WebhookDeliveryStats) GetTotal() int64 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *WebhookDeliveryStats) GetFailed() int64 {
	if x != nil {
		return x.xxx_hidden_Failed
	}
	return 0
}

func (x *WebhookDeliveryStats) GetDurationMs() *WebhookDeliveryDurationStats {
	if x != nil {
		return x.xxx_hidden_DurationMs
	}
	return nil
}

func (x *WebhookDeliveryStats) SetBuckets(v []*WebhookDeliveryStatsBucket) {
	x.xxx_hidden_Buckets = &v
}

func (x *WebhookDeliveryStats) SetTotal(v int64) {
	x.xxx_hidden_Total = v
}

func (x *WebhookDeliveryStats) SetFailed(v int64) {
	x.xxx_hidden_Failed = v
}

func (x *WebhookDeliveryStats) SetDurationMs(v *WebhookDeliveryDurationStats) {
	x.xxx_hidden_DurationMs = v
}

func (x *WebhookDeliveryStats) HasDurationMs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DurationMs != nil
}

func (x *WebhookDeliveryStats) ClearDurationMs() {
	x.xxx_hidden_DurationMs = nil
}

type WebhookDeliveryStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Buckets    []*WebhookDeliveryStatsBucket
	Total      int64
	Failed     int64
	DurationMs *WebhookDeliveryDurationStats
}

func (b0 WebhookDeliveryStats_builder) Build() *WebhookDeliveryStats {
	m0 := &WebhookDeliveryStats{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Buckets = &b.Buckets
	x.xxx_hidden_Total = b.Total
	x.xxx_hidden_Failed = b.Failed
	x.xxx_hidden_DurationMs = b.DurationMs
	return m0
}

type WebhookDeliveryStatsBucket struct {
	state                 protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Timestamp  *timestamppb.Timestamp        `protobuf:"bytes,1,opt,name=timestamp"`
	xxx_hidden_Total      int64                         `protobuf:"varint,2,opt,name=total"`
	xxx_hidden_Failed     int64                         `protobuf:"varint,3,opt,name=failed"`
	xxx_hidden_DurationMs *WebhookDeliveryDurationStats `protobuf:"bytes,4,opt,name=duration_ms,json=durationMs"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WebhookDeliveryStatsBucket) Reset() {
	*x = WebhookDeliveryStatsBucket{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDeliveryStatsBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDeliveryStatsBucket) ProtoMessage() {}

func (x *WebhookDeliveryStatsBucket) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebhookDeliveryStatsBucket) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *WebhookDeliveryStatsBucket) GetTotal() int64 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *WebhookDeliveryStatsBucket) GetFailed() int64 {
	if x != nil {
		return x.xxx_hidden_Failed
	}
	return 0
}

func (x *WebhookDeliveryStatsBucket) GetDurationMs() *WebhookDeliveryDurationStats {
	if x != nil {
		return x.xxx_hidden_DurationMs
	}
	return nil
}

func (x *WebhookDeliveryStatsBucket) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *WebhookDeliveryStatsBucket) SetTotal(v int64) {
	x.xxx_hidden_Total = v
}

func (x *WebhookDeliveryStatsBucket) SetFailed(v int64) {
	x.xxx_hidden_Failed = v
}

func (x *WebhookDeliveryStatsBucket) SetDurationMs(v *WebhookDeliveryDurationStats) {
	x.xxx_hidden_DurationMs = v
}

func (x *WebhookDeliveryStatsBucket) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *WebhookDeliveryStatsBucket) HasDurationMs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DurationMs != nil
}

func (x *WebhookDeliveryStatsBucket) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *WebhookDeliveryStatsBucket) ClearDurationMs() {
	x.xxx_hidden_DurationMs = nil
}

type WebhookDeliveryStatsBucket_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Timestamp  *timestamppb.Timestamp
	Total      int64
	Failed     int64
	DurationMs *WebhookDeliveryDurationStats
}

func (b0 WebhookDeliveryStatsBucket_builder) Build() *WebhookDeliveryStatsBucket {
	m0 := &WebhookDeliveryStatsBucket{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Total = b.Total
	x.xxx_hidden_Failed = b.Failed
	x.xxx_hidden_DurationMs = b.DurationMs
	return m0
}

type WebhookDeliveryDurationStats struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Minimum float64                `protobuf:"fixed64,1,opt,name=minimum"`
	xxx_hidden_Average float64                `protobuf:"fixed64,2,opt,name=average"`
	xxx_hidden_Maximum float64                `protobuf:"fixed64,3,opt,name=maximum"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebhookDeliveryDurationStats) Reset() {
	*x = WebhookDeliveryDurationStats{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDeliveryDurationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDeliveryDurationStats) ProtoMessage() {}

func (x *WebhookDeliveryDurationStats) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebhookDeliveryDurationStats) GetMinimum() float64 {
	if x != nil {
		return x.xxx_hidden_Minimum
	}
	return 0
}

func (x *WebhookDeliveryDurationStats) GetAverage() float64 {
	if x != nil {
		return x.xxx_hidden_Average
	}
	return 0
}

func (x *WebhookDeliveryDurationStats) GetMaximum() float64 {
	if x != nil {
		return x.xxx_hidden_Maximum
	}
	return 0
}

func (x *WebhookDeliveryDurationStats) SetMinimum(v float64) {
	x.xxx_hidden_Minimum = v
}

func (x *WebhookDeliveryDurationStats) SetAverage(v float64) {
	x.xxx_hidden_Average = v
}

func (x *WebhookDeliveryDurationStats) SetMaximum(v float64) {
	x.xxx_hidden_Maximum = v
}

type WebhookDeliveryDurationStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Minimum float64
	Average float64
	Maximum float64
}

func (b0 WebhookDeliveryDurationStats_builder) Build() *WebhookDeliveryDurationStats {
	m0 := &WebhookDeliveryDurationStats{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Minimum = b.Minimum
	x.xxx_hidden_Average = b.Average
	x.xxx_hidden_Maximum = b.Maximum
	return m0
}

type WebhookManagementErrorDetail struct {
	state             protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Reason WebhookManagementErrorReason `protobuf:"varint,1,opt,name=reason,enum=e2b.webhooks.management.v1.WebhookManagementErrorReason"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebhookManagementErrorDetail) Reset() {
	*x = WebhookManagementErrorDetail{}
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookManagementErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookManagementErrorDetail) ProtoMessage() {}

func (x *WebhookManagementErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebhookManagementErrorDetail) GetReason() WebhookManagementErrorReason {
	if x != nil {
		return x.xxx_hidden_Reason
	}
	return WebhookManagementErrorReason_WEBHOOK_MANAGEMENT_ERROR_REASON_UNSPECIFIED
}

func (x *WebhookManagementErrorDetail) SetReason(v WebhookManagementErrorReason) {
	x.xxx_hidden_Reason = v
}

type WebhookManagementErrorDetail_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Reason WebhookManagementErrorReason
}

func (b0 WebhookManagementErrorDetail_builder) Build() *WebhookManagementErrorDetail {
	m0 := &WebhookManagementErrorDetail{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Reason = b.Reason
	return m0
}

var File_e2b_webhooks_management_v1_webhook_management_proto protoreflect.FileDescriptor

const file_e2b_webhooks_management_v1_webhook_management_proto_rawDesc = "" +
	"\n" +
	"3e2b/webhooks/management/v1/webhook_management.proto\x12\x1ae2b.webhooks.management.v1\x1a\x1bbuf/validate/validate.proto\x1a-e2b/validate/v1/predefined_string_rules.proto\x1a0e2b/validate/v1/predefined_timestamp_rules.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\aWebhook\x12'\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\twebhookId\x12!\n" +
	"\ateam_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x16\n" +
	"\x06events\x18\a \x03(\tR\x06events\"\xcc\x02\n" +
	"\x14CreateWebhookRequest\x12!\n" +
	"\ateam_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x12,\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB\r\xbaH\x05r\x03\xb0\x01\x01\xaa\x01\x02\b\x01R\tclusterId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\x03url\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x80\xb5\x18\x01R\x03url\x12f\n" +
	"\x06events\x18\x05 \x03(\tBN\xbaHK\xba\x01H\n" +
	"\x0fevents.required\x12$must specify at least one event type\x1a\x0fthis.size() > 0R\x06events\x12\x1f\n" +
	"\aenabled\x18\x06 \x01(\bB\x05\xaa\x01\x02\b\x01R\aenabled\x12)\n" +
	"\x10signature_secret\x18\a \x01(\tR\x0fsignatureSecret\"V\n" +
	"\x15CreateWebhookResponse\x12=\n" +
	"\awebhook\x18\x01 \x01(\v2#.e2b.webhooks.management.v1.WebhookR\awebhook\"8\n" +
	"\x13ListWebhooksRequest\x12!\n" +
	"\ateam_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\"W\n" +
	"\x14ListWebhooksResponse\x12?\n" +
	"\bwebhooks\x18\x01 \x03(\v2#.e2b.webhooks.management.v1.WebhookR\bwebhooks\"_\n" +
	"\x11GetWebhookRequest\x12!\n" +
	"\ateam_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x12'\n" +
	"\n" +
	"webhook_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\twebhookId\"S\n" +
	"\x12GetWebhookResponse\x12=\n" +
	"\awebhook\x18\x01 \x01(\v2#.e2b.webhooks.management.v1.WebhookR\awebhook\"-\n" +
	"\x13WebhookEventsUpdate\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xc1\x03\n" +
	"\x14UpdateWebhookRequest\x12!\n" +
	"\ateam_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x12,\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB\r\xbaH\x05r\x03\xb0\x01\x01\xaa\x01\x02\b\x01R\tclusterId\x12'\n" +
	"\n" +
	"webhook_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\twebhookId\x12\x19\n" +
	"\x04name\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x01R\x04name\x12 \n" +
	"\x03url\x18\x05 \x01(\tB\x0e\xbaH\x06r\x04\x80\xb5\x18\x01\xaa\x01\x02\b\x01R\x03url\x12\x9e\x01\n" +
	"\x06events\x18\x06 \x01(\v2/.e2b.webhooks.management.v1.WebhookEventsUpdateBU\xbaHR\xba\x01O\n" +
	"\x0fevents.required\x12$must specify at least one event type\x1a\x16this.values.size() > 0R\x06events\x12\x1f\n" +
	"\aenabled\x18\a \x01(\bB\x05\xaa\x01\x02\b\x01R\aenabled\x120\n" +
	"\x10signature_secret\x18\b \x01(\tB\x05\xaa\x01\x02\b\x01R\x0fsignatureSecret\"V\n" +
	"\x15UpdateWebhookResponse\x12=\n" +
	"\awebhook\x18\x01 \x01(\v2#.e2b.webhooks.management.v1.WebhookR\awebhook\"\x90\x01\n" +
	"\x14DeleteWebhookRequest\x12!\n" +
	"\ateam_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x12,\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB\r\xbaH\x05r\x03\xb0\x01\x01\xaa\x01\x02\b\x01R\tclusterId\x12'\n" +
	"\n" +
	"webhook_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\twebhookId\"\x17\n" +
	"\x15DeleteWebhookResponse\"\xe3\x03\n" +
	"\x1cListWebhookDeliveriesRequest\x12!\n" +
	"\ateam_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x12,\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB\r\xbaH\x05r\x03\xb0\x01\x01\xaa\x01\x02\b\x01R\tclusterId\x12'\n" +
	"\n" +
	"webhook_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\twebhookId\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x1b\n" +
	"\x05limit\x18\x05 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05limit\x12\x1b\n" +
	"\torder_asc\x18\x06 \x01(\bR\borderAsc\x12<\n" +
	"\x05start\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xbaH\a\xb2\x01\x04\x80\xb5\x18\x01R\x05start\x128\n" +
	"\x03end\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xbaH\a\xb2\x01\x04\x80\xb5\x18\x01R\x03end\x12^\n" +
	"\x11delivery_statuses\x18\t \x03(\x0e21.e2b.webhooks.management.v1.WebhookDeliveryStatusR\x10deliveryStatuses\x12\x1f\n" +
	"\vevent_types\x18\n" +
	" \x03(\tR\n" +
	"eventTypes\"\x91\x01\n" +
	"\x1dListWebhookDeliveriesResponse\x12H\n" +
	"\x06groups\x18\x01 \x03(\v20.e2b.webhooks.management.v1.WebhookDeliveryGroupR\x06groups\x12&\n" +
	"\vnext_cursor\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x01R\n" +
	"nextCursor\"\xc2\x01\n" +
	"\x14WebhookDeliveryGroup\x12#\n" +
	"\bevent_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x03 \x01(\tR\tsandboxId\x12G\n" +
	"\battempts\x18\x04 \x03(\v2+.e2b.webhooks.management.v1.WebhookDeliveryR\battempts\"\xa9\x06\n" +
	"\x0fWebhookDelivery\x12)\n" +
	"\vdelivery_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"deliveryId\x12!\n" +
	"\ateam_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x12'\n" +
	"\n" +
	"webhook_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\twebhookId\x12#\n" +
	"\bevent_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aeventId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x05 \x01(\tR\tsandboxId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12I\n" +
	"\x06status\x18\a \x01(\x0e21.e2b.webhooks.management.v1.WebhookDeliveryStatusR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x05R\n" +
	"durationMs\x12!\n" +
	"\frequest_body\x18\t \x01(\tR\vrequestBody\x12'\n" +
	"\x0frequest_headers\x18\n" +
	" \x01(\tR\x0erequestHeaders\x12\x1f\n" +
	"\vrequest_url\x18\v \x01(\tR\n" +
	"requestUrl\x12*\n" +
	"\rresponse_body\x18\f \x01(\tB\x05\xaa\x01\x02\b\x01R\fresponseBody\x120\n" +
	"\x10response_headers\x18\r \x01(\tB\x05\xaa\x01\x02\b\x01R\x0fresponseHeaders\x12@\n" +
	"\x19response_http_status_code\x18\x0e \x01(\x05B\x05\xaa\x01\x02\b\x01R\x16responseHttpStatusCode\x12]\n" +
	"\verror_class\x18\x0f \x01(\x0e25.e2b.webhooks.management.v1.WebhookDeliveryErrorClassB\x05\xaa\x01\x02\b\x01R\n" +
	"errorClass\x12*\n" +
	"\rerror_message\x18\x10 \x01(\tB\x05\xaa\x01\x02\b\x01R\ferrorMessage\x128\n" +
	"\ttimestamp\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x92\x02\n" +
	"\x1eGetWebhookDeliveryStatsRequest\x12!\n" +
	"\ateam_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x12,\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB\r\xbaH\x05r\x03\xb0\x01\x01\xaa\x01\x02\b\x01R\tclusterId\x12'\n" +
	"\n" +
	"webhook_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\twebhookId\x12<\n" +
	"\x05start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xbaH\a\xb2\x01\x04\x80\xb5\x18\x01R\x05start\x128\n" +
	"\x03end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xbaH\a\xb2\x01\x04\x80\xb5\x18\x01R\x03end\"i\n" +
	"\x1fGetWebhookDeliveryStatsResponse\x12F\n" +
	"\x05stats\x18\x01 \x01(\v20.e2b.webhooks.management.v1.WebhookDeliveryStatsR\x05stats\"\xf1\x01\n" +
	"\x14WebhookDeliveryStats\x12P\n" +
	"\abuckets\x18\x01 \x03(\v26.e2b.webhooks.management.v1.WebhookDeliveryStatsBucketR\abuckets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x03R\x06failed\x12Y\n" +
	"\vduration_ms\x18\x04 \x01(\v28.e2b.webhooks.management.v1.WebhookDeliveryDurationStatsR\n" +
	"durationMs\"\xdf\x01\n" +
	"\x1aWebhookDeliveryStatsBucket\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x03R\x06failed\x12Y\n" +
	"\vduration_ms\x18\x04 \x01(\v28.e2b.webhooks.management.v1.WebhookDeliveryDurationStatsR\n" +
	"durationMs\"l\n" +
	"\x1cWebhookDeliveryDurationStats\x12\x18\n" +
	"\aminimum\x18\x01 \x01(\x01R\aminimum\x12\x18\n" +
	"\aaverage\x18\x02 \x01(\x01R\aaverage\x12\x18\n" +
	"\amaximum\x18\x03 \x01(\x01R\amaximum\"p\n" +
	"\x1cWebhookManagementErrorDetail\x12P\n" +
	"\x06reason\x18\x01 \x01(\x0e28.e2b.webhooks.management.v1.WebhookManagementErrorReasonR\x06reason*\x89\x01\n" +
	"\x15WebhookDeliveryStatus\x12'\n" +
	"#WEBHOOK_DELIVERY_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fWEBHOOK_DELIVERY_STATUS_SUCCESS\x10\x01\x12\"\n" +
	"\x1eWEBHOOK_DELIVERY_STATUS_FAILED\x10\x02*\x8b\x03\n" +
	"\x19WebhookDeliveryErrorClass\x12,\n" +
	"(WEBHOOK_DELIVERY_ERROR_CLASS_UNSPECIFIED\x10\x00\x12+\n" +
	"'WEBHOOK_DELIVERY_ERROR_CLASS_HTTP_ERROR\x10\x01\x12*\n" +
	"&WEBHOOK_DELIVERY_ERROR_CLASS_DNS_ERROR\x10\x02\x12(\n" +
	"$WEBHOOK_DELIVERY_ERROR_CLASS_TIMEOUT\x10\x03\x120\n" +
	",WEBHOOK_DELIVERY_ERROR_CLASS_TRANSPORT_ERROR\x10\x04\x12.\n" +
	"*WEBHOOK_DELIVERY_ERROR_CLASS_REQUEST_ERROR\x10\x05\x120\n" +
	",WEBHOOK_DELIVERY_ERROR_CLASS_SIGNATURE_ERROR\x10\x06\x12)\n" +
	"%WEBHOOK_DELIVERY_ERROR_CLASS_CANCELED\x10\a*\x8a\x01\n" +
	"\x1cWebhookManagementErrorReason\x12/\n" +
	"+WEBHOOK_MANAGEMENT_ERROR_REASON_UNSPECIFIED\x10\x00\x129\n" +
	"5WEBHOOK_MANAGEMENT_ERROR_REASON_WEBHOOK_LIMIT_REACHED\x10\x012\x80\a\n" +
	"\x18WebhookManagementService\x12t\n" +
	"\rCreateWebhook\x120.e2b.webhooks.management.v1.CreateWebhookRequest\x1a1.e2b.webhooks.management.v1.CreateWebhookResponse\x12q\n" +
	"\fListWebhooks\x12/.e2b.webhooks.management.v1.ListWebhooksRequest\x1a0.e2b.webhooks.management.v1.ListWebhooksResponse\x12k\n" +
	"\n" +
	"GetWebhook\x12-.e2b.webhooks.management.v1.GetWebhookRequest\x1a..e2b.webhooks.management.v1.GetWebhookResponse\x12t\n" +
	"\rUpdateWebhook\x120.e2b.webhooks.management.v1.UpdateWebhookRequest\x1a1.e2b.webhooks.management.v1.UpdateWebhookResponse\x12t\n" +
	"\rDeleteWebhook\x120.e2b.webhooks.management.v1.DeleteWebhookRequest\x1a1.e2b.webhooks.management.v1.DeleteWebhookResponse\x12\x8c\x01\n" +
	"\x15ListWebhookDeliveries\x128.e2b.webhooks.management.v1.ListWebhookDeliveriesRequest\x1a9.e2b.webhooks.management.v1.ListWebhookDeliveriesResponse\x12\x92\x01\n" +
	"\x17GetWebhookDeliveryStats\x12:.e2b.webhooks.management.v1.GetWebhookDeliveryStatsRequest\x1a;.e2b.webhooks.management.v1.GetWebhookDeliveryStatsResponseB\x05\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_e2b_webhooks_management_v1_webhook_management_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_e2b_webhooks_management_v1_webhook_management_proto_goTypes = []any{
	(WebhookDeliveryStatus)(0),              // 0: e2b.webhooks.management.v1.WebhookDeliveryStatus
	(WebhookDeliveryErrorClass)(0),          // 1: e2b.webhooks.management.v1.WebhookDeliveryErrorClass
	(WebhookManagementErrorReason)(0),       // 2: e2b.webhooks.management.v1.WebhookManagementErrorReason
	(*Webhook)(nil),                         // 3: e2b.webhooks.management.v1.Webhook
	(*CreateWebhookRequest)(nil),            // 4: e2b.webhooks.management.v1.CreateWebhookRequest
	(*CreateWebhookResponse)(nil),           // 5: e2b.webhooks.management.v1.CreateWebhookResponse
	(*ListWebhooksRequest)(nil),             // 6: e2b.webhooks.management.v1.ListWebhooksRequest
	(*ListWebhooksResponse)(nil),            // 7: e2b.webhooks.management.v1.ListWebhooksResponse
	(*GetWebhookRequest)(nil),               // 8: e2b.webhooks.management.v1.GetWebhookRequest
	(*GetWebhookResponse)(nil),              // 9: e2b.webhooks.management.v1.GetWebhookResponse
	(*WebhookEventsUpdate)(nil),             // 10: e2b.webhooks.management.v1.WebhookEventsUpdate
	(*UpdateWebhookRequest)(nil),            // 11: e2b.webhooks.management.v1.UpdateWebhookRequest
	(*UpdateWebhookResponse)(nil),           // 12: e2b.webhooks.management.v1.UpdateWebhookResponse
	(*DeleteWebhookRequest)(nil),            // 13: e2b.webhooks.management.v1.DeleteWebhookRequest
	(*DeleteWebhookResponse)(nil),           // 14: e2b.webhooks.management.v1.DeleteWebhookResponse
	(*ListWebhookDeliveriesRequest)(nil),    // 15: e2b.webhooks.management.v1.ListWebhookDeliveriesRequest
	(*ListWebhookDeliveriesResponse)(nil),   // 16: e2b.webhooks.management.v1.ListWebhookDeliveriesResponse
	(*WebhookDeliveryGroup)(nil),            // 17: e2b.webhooks.management.v1.WebhookDeliveryGroup
	(*WebhookDelivery)(nil),                 // 18: e2b.webhooks.management.v1.WebhookDelivery
	(*GetWebhookDeliveryStatsRequest)(nil),  // 19: e2b.webhooks.management.v1.GetWebhookDeliveryStatsRequest
	(*GetWebhookDeliveryStatsResponse)(nil), // 20: e2b.webhooks.management.v1.GetWebhookDeliveryStatsResponse
	(*WebhookDeliveryStats)(nil),            // 21: e2b.webhooks.management.v1.WebhookDeliveryStats
	(*WebhookDeliveryStatsBucket)(nil),      // 22: e2b.webhooks.management.v1.WebhookDeliveryStatsBucket
	(*WebhookDeliveryDurationStats)(nil),    // 23: e2b.webhooks.management.v1.WebhookDeliveryDurationStats
	(*WebhookManagementErrorDetail)(nil),    // 24: e2b.webhooks.management.v1.WebhookManagementErrorDetail
	(*timestamppb.Timestamp)(nil),           // 25: google.protobuf.Timestamp
}
var file_e2b_webhooks_management_v1_webhook_management_proto_depIdxs = []int32{
	25, // 0: e2b.webhooks.management.v1.Webhook.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: e2b.webhooks.management.v1.CreateWebhookResponse.webhook:type_name -> e2b.webhooks.management.v1.Webhook
	3,  // 2: e2b.webhooks.management.v1.ListWebhooksResponse.webhooks:type_name -> e2b.webhooks.management.v1.Webhook
	3,  // 3: e2b.webhooks.management.v1.GetWebhookResponse.webhook:type_name -> e2b.webhooks.management.v1.Webhook
	10, // 4: e2b.webhooks.management.v1.UpdateWebhookRequest.events:type_name -> e2b.webhooks.management.v1.WebhookEventsUpdate
	3,  // 5: e2b.webhooks.management.v1.UpdateWebhookResponse.webhook:type_name -> e2b.webhooks.management.v1.Webhook
	25, // 6: e2b.webhooks.management.v1.ListWebhookDeliveriesRequest.start:type_name -> google.protobuf.Timestamp
	25, // 7: e2b.webhooks.management.v1.ListWebhookDeliveriesRequest.end:type_name -> google.protobuf.Timestamp
	0,  // 8: e2b.webhooks.management.v1.ListWebhookDeliveriesRequest.delivery_statuses:type_name -> e2b.webhooks.management.v1.WebhookDeliveryStatus
	17, // 9: e2b.webhooks.management.v1.ListWebhookDeliveriesResponse.groups:type_name -> e2b.webhooks.management.v1.WebhookDeliveryGroup
	18, // 10: e2b.webhooks.management.v1.WebhookDeliveryGroup.attempts:type_name -> e2b.webhooks.management.v1.WebhookDelivery
	0,  // 11: e2b.webhooks.management.v1.WebhookDelivery.status:type_name -> e2b.webhooks.management.v1.WebhookDeliveryStatus
	1,  // 12: e2b.webhooks.management.v1.WebhookDelivery.error_class:type_name -> e2b.webhooks.management.v1.WebhookDeliveryErrorClass
	25, // 13: e2b.webhooks.management.v1.WebhookDelivery.timestamp:type_name -> google.protobuf.Timestamp
	25, // 14: e2b.webhooks.management.v1.GetWebhookDeliveryStatsRequest.start:type_name -> google.protobuf.Timestamp
	25, // 15: e2b.webhooks.management.v1.GetWebhookDeliveryStatsRequest.end:type_name -> google.protobuf.Timestamp
	21, // 16: e2b.webhooks.management.v1.GetWebhookDeliveryStatsResponse.stats:type_name -> e2b.webhooks.management.v1.WebhookDeliveryStats
	22, // 17: e2b.webhooks.management.v1.WebhookDeliveryStats.buckets:type_name -> e2b.webhooks.management.v1.WebhookDeliveryStatsBucket
	23, // 18: e2b.webhooks.management.v1.WebhookDeliveryStats.duration_ms:type_name -> e2b.webhooks.management.v1.WebhookDeliveryDurationStats
	25, // 19: e2b.webhooks.management.v1.WebhookDeliveryStatsBucket.timestamp:type_name -> google.protobuf.Timestamp
	23, // 20: e2b.webhooks.management.v1.WebhookDeliveryStatsBucket.duration_ms:type_name -> e2b.webhooks.management.v1.WebhookDeliveryDurationStats
	2,  // 21: e2b.webhooks.management.v1.WebhookManagementErrorDetail.reason:type_name -> e2b.webhooks.management.v1.WebhookManagementErrorReason
	4,  // 22: e2b.webhooks.management.v1.WebhookManagementService.CreateWebhook:input_type -> e2b.webhooks.management.v1.CreateWebhookRequest
	6,  // 23: e2b.webhooks.management.v1.WebhookManagementService.ListWebhooks:input_type -> e2b.webhooks.management.v1.ListWebhooksRequest
	8,  // 24: e2b.webhooks.management.v1.WebhookManagementService.GetWebhook:input_type -> e2b.webhooks.management.v1.GetWebhookRequest
	11, // 25: e2b.webhooks.management.v1.WebhookManagementService.UpdateWebhook:input_type -> e2b.webhooks.management.v1.UpdateWebhookRequest
	13, // 26: e2b.webhooks.management.v1.WebhookManagementService.DeleteWebhook:input_type -> e2b.webhooks.management.v1.DeleteWebhookRequest
	15, // 27: e2b.webhooks.management.v1.WebhookManagementService.ListWebhookDeliveries:input_type -> e2b.webhooks.management.v1.ListWebhookDeliveriesRequest
	19, // 28: e2b.webhooks.management.v1.WebhookManagementService.GetWebhookDeliveryStats:input_type -> e2b.webhooks.management.v1.GetWebhookDeliveryStatsRequest
	5,  // 29: e2b.webhooks.management.v1.WebhookManagementService.CreateWebhook:output_type -> e2b.webhooks.management.v1.CreateWebhookResponse
	7,  // 30: e2b.webhooks.management.v1.WebhookManagementService.ListWebhooks:output_type -> e2b.webhooks.management.v1.ListWebhooksResponse
	9,  // 31: e2b.webhooks.management.v1.WebhookManagementService.GetWebhook:output_type -> e2b.webhooks.management.v1.GetWebhookResponse
	12, // 32: e2b.webhooks.management.v1.WebhookManagementService.UpdateWebhook:output_type -> e2b.webhooks.management.v1.UpdateWebhookResponse
	14, // 33: e2b.webhooks.management.v1.WebhookManagementService.DeleteWebhook:output_type -> e2b.webhooks.management.v1.DeleteWebhookResponse
	16, // 34: e2b.webhooks.management.v1.WebhookManagementService.ListWebhookDeliveries:output_type -> e2b.webhooks.management.v1.ListWebhookDeliveriesResponse
	20, // 35: e2b.webhooks.management.v1.WebhookManagementService.GetWebhookDeliveryStats:output_type -> e2b.webhooks.management.v1.GetWebhookDeliveryStatsResponse
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_e2b_webhooks_management_v1_webhook_management_proto_init() }
func file_e2b_webhooks_management_v1_webhook_management_proto_init() {
	if File_e2b_webhooks_management_v1_webhook_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e2b_webhooks_management_v1_webhook_management_proto_rawDesc), len(file_e2b_webhooks_management_v1_webhook_management_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_e2b_webhooks_management_v1_webhook_management_proto_goTypes,
		DependencyIndexes: file_e2b_webhooks_management_v1_webhook_management_proto_depIdxs,
		EnumInfos:         file_e2b_webhooks_management_v1_webhook_management_proto_enumTypes,
		MessageInfos:      file_e2b_webhooks_management_v1_webhook_management_proto_msgTypes,
	}.Build()
	File_e2b_webhooks_management_v1_webhook_management_proto = out.File
	file_e2b_webhooks_management_v1_webhook_management_proto_goTypes = nil
	file_e2b_webhooks_management_v1_webhook_management_proto_depIdxs = nil
}
