// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: e2b/webhooks/management/v1/webhook_management.proto

package management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookManagementService_CreateWebhook_FullMethodName           = "/e2b.webhooks.management.v1.WebhookManagementService/CreateWebhook"
	WebhookManagementService_ListWebhooks_FullMethodName            = "/e2b.webhooks.management.v1.WebhookManagementService/ListWebhooks"
	WebhookManagementService_GetWebhook_FullMethodName              = "/e2b.webhooks.management.v1.WebhookManagementService/GetWebhook"
	WebhookManagementService_UpdateWebhook_FullMethodName           = "/e2b.webhooks.management.v1.WebhookManagementService/UpdateWebhook"
	WebhookManagementService_DeleteWebhook_FullMethodName           = "/e2b.webhooks.management.v1.WebhookManagementService/DeleteWebhook"
	WebhookManagementService_ListWebhookDeliveries_FullMethodName   = "/e2b.webhooks.management.v1.WebhookManagementService/ListWebhookDeliveries"
	WebhookManagementService_GetWebhookDeliveryStats_FullMethodName = "/e2b.webhooks.management.v1.WebhookManagementService/GetWebhookDeliveryStats"
)

// WebhookManagementServiceClient is the client API for WebhookManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Manages team-scoped webhooks and reads their delivery history.
//
// The caller authenticates the user and supplies the resulting team and cluster
// identifiers. Reaching this service is the access-control boundary; any caller
// that can connect can act for any team it names.
//
// A successful mutation means the webhook record was persisted. Propagation to
// the team's cluster happens asynchronously.
type WebhookManagementServiceClient interface {
	CreateWebhook(ctx context.Context, in *CreateWebhookRequest, opts ...grpc.CallOption) (*CreateWebhookResponse, error)
	ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error)
	GetWebhook(ctx context.Context, in *GetWebhookRequest, opts ...grpc.CallOption) (*GetWebhookResponse, error)
	UpdateWebhook(ctx context.Context, in *UpdateWebhookRequest, opts ...grpc.CallOption) (*UpdateWebhookResponse, error)
	DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*DeleteWebhookResponse, error)
	ListWebhookDeliveries(ctx context.Context, in *ListWebhookDeliveriesRequest, opts ...grpc.CallOption) (*ListWebhookDeliveriesResponse, error)
	GetWebhookDeliveryStats(ctx context.Context, in *GetWebhookDeliveryStatsRequest, opts ...grpc.CallOption) (*GetWebhookDeliveryStatsResponse, error)
}

type webhookManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookManagementServiceClient(cc grpc.ClientConnInterface) WebhookManagementServiceClient {
	return &webhookManagementServiceClient{cc}
}

func (c *webhookManagementServiceClient) CreateWebhook(ctx context.Context, in *CreateWebhookRequest, opts ...grpc.CallOption) (*CreateWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookManagementService_CreateWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookManagementServiceClient) ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebhooksResponse)
	err := c.cc.Invoke(ctx, WebhookManagementService_ListWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookManagementServiceClient) GetWebhook(ctx context.Context, in *GetWebhookRequest, opts ...grpc.CallOption) (*GetWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookManagementService_GetWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookManagementServiceClient) UpdateWebhook(ctx context.Context, in *UpdateWebhookRequest, opts ...grpc.CallOption) (*UpdateWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookManagementService_UpdateWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookManagementServiceClient) DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*DeleteWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookManagementService_DeleteWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookManagementServiceClient) ListWebhookDeliveries(ctx context.Context, in *ListWebhookDeliveriesRequest, opts ...grpc.CallOption) (*ListWebhookDeliveriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebhookDeliveriesResponse)
	err := c.cc.Invoke(ctx, WebhookManagementService_ListWebhookDeliveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookManagementServiceClient) GetWebhookDeliveryStats(ctx context.Context, in *GetWebhookDeliveryStatsRequest, opts ...grpc.CallOption) (*GetWebhookDeliveryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookDeliveryStatsResponse)
	err := c.cc.Invoke(ctx, WebhookManagementService_GetWebhookDeliveryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookManagementServiceServer is the server API for WebhookManagementService service.
// All implementations must embed UnimplementedWebhookManagementServiceServer
// for forward compatibility.
//
// Manages team-scoped webhooks and reads their delivery history.
//
// The caller authenticates the user and supplies the resulting team and cluster
// identifiers. Reaching this service is the access-control boundary; any caller
// that can connect can act for any team it names.
//
// A successful mutation means the webhook record was persisted. Propagation to
// the team's cluster happens asynchronously.
type WebhookManagementServiceServer interface {
	CreateWebhook(context.Context, *CreateWebhookRequest) (*CreateWebhookResponse, error)
	ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error)
	GetWebhook(context.Context, *GetWebhookRequest) (*GetWebhookResponse, error)
	UpdateWebhook(context.Context, *UpdateWebhookRequest) (*UpdateWebhookResponse, error)
	DeleteWebhook(context.Context, *DeleteWebhookRequest) (*DeleteWebhookResponse, error)
	ListWebhookDeliveries(context.Context, *ListWebhookDeliveriesRequest) (*ListWebhookDeliveriesResponse, error)
	GetWebhookDeliveryStats(context.Context, *GetWebhookDeliveryStatsRequest) (*GetWebhookDeliveryStatsResponse, error)
	mustEmbedUnimplementedWebhookManagementServiceServer()
}

// UnimplementedWebhookManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookManagementServiceServer struct{}

func (UnimplementedWebhookManagementServiceServer) CreateWebhook(context.Context, *CreateWebhookRequest) (*CreateWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWebhook not implemented")
}
func (UnimplementedWebhookManagementServiceServer) ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebhooks not implemented")
}
func (UnimplementedWebhookManagementServiceServer) GetWebhook(context.Context, *GetWebhookRequest) (*GetWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhook not implemented")
}
func (UnimplementedWebhookManagementServiceServer) UpdateWebhook(context.Context, *UpdateWebhookRequest) (*UpdateWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWebhook not implemented")
}
func (UnimplementedWebhookManagementServiceServer) DeleteWebhook(context.Context, *DeleteWebhookRequest) (*DeleteWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWebhook not implemented")
}
func (UnimplementedWebhookManagementServiceServer) ListWebhookDeliveries(context.Context, *ListWebhookDeliveriesRequest) (*ListWebhookDeliveriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebhookDeliveries not implemented")
}
func (UnimplementedWebhookManagementServiceServer) GetWebhookDeliveryStats(context.Context, *GetWebhookDeliveryStatsRequest) (*GetWebhookDeliveryStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhookDeliveryStats not implemented")
}
func (UnimplementedWebhookManagementServiceServer) mustEmbedUnimplementedWebhookManagementServiceServer() {
}
func (UnimplementedWebhookManagementServiceServer) testEmbeddedByValue() {}

// UnsafeWebhookManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookManagementServiceServer will
// result in compilation errors.
type UnsafeWebhookManagementServiceServer interface {
	mustEmbedUnimplementedWebhookManagementServiceServer()
}

func RegisterWebhookManagementServiceServer(s grpc.ServiceRegistrar, srv WebhookManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedWebhookManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookManagementService_ServiceDesc, srv)
}

func _WebhookManagementService_CreateWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookManagementServiceServer).CreateWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookManagementService_CreateWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookManagementServiceServer).CreateWebhook(ctx, req.(*CreateWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookManagementService_ListWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookManagementServiceServer).ListWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookManagementService_ListWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookManagementServiceServer).ListWebhooks(ctx, req.(*ListWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookManagementService_GetWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookManagementServiceServer).GetWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookManagementService_GetWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookManagementServiceServer).GetWebhook(ctx, req.(*GetWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookManagementService_UpdateWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookManagementServiceServer).UpdateWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookManagementService_UpdateWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookManagementServiceServer).UpdateWebhook(ctx, req.(*UpdateWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookManagementService_DeleteWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookManagementServiceServer).DeleteWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookManagementService_DeleteWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookManagementServiceServer).DeleteWebhook(ctx, req.(*DeleteWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookManagementService_ListWebhookDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhookDeliveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookManagementServiceServer).ListWebhookDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookManagementService_ListWebhookDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookManagementServiceServer).ListWebhookDeliveries(ctx, req.(*ListWebhookDeliveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookManagementService_GetWebhookDeliveryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookDeliveryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookManagementServiceServer).GetWebhookDeliveryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookManagementService_GetWebhookDeliveryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookManagementServiceServer).GetWebhookDeliveryStats(ctx, req.(*GetWebhookDeliveryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookManagementService_ServiceDesc is the grpc.ServiceDesc for WebhookManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "e2b.webhooks.management.v1.WebhookManagementService",
	HandlerType: (*WebhookManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWebhook",
			Handler:    _WebhookManagementService_CreateWebhook_Handler,
		},
		{
			MethodName: "ListWebhooks",
			Handler:    _WebhookManagementService_ListWebhooks_Handler,
		},
		{
			MethodName: "GetWebhook",
			Handler:    _WebhookManagementService_GetWebhook_Handler,
		},
		{
			MethodName: "UpdateWebhook",
			Handler:    _WebhookManagementService_UpdateWebhook_Handler,
		},
		{
			MethodName: "DeleteWebhook",
			Handler:    _WebhookManagementService_DeleteWebhook_Handler,
		},
		{
			MethodName: "ListWebhookDeliveries",
			Handler:    _WebhookManagementService_ListWebhookDeliveries_Handler,
		},
		{
			MethodName: "GetWebhookDeliveryStats",
			Handler:    _WebhookManagementService_GetWebhookDeliveryStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "e2b/webhooks/management/v1/webhook_management.proto",
}
