// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: e2b/webhooks/events/v1/sandbox_events.proto

package events

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxEvent struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventId            string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId"`
	xxx_hidden_Version            string                 `protobuf:"bytes,2,opt,name=version"`
	xxx_hidden_Type               string                 `protobuf:"bytes,3,opt,name=type"`
	xxx_hidden_Timestamp          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp"`
	xxx_hidden_EventCategory      *string                `protobuf:"bytes,5,opt,name=event_category,json=eventCategory"`
	xxx_hidden_EventLabel         *string                `protobuf:"bytes,6,opt,name=event_label,json=eventLabel"`
	xxx_hidden_EventData          *structpb.Struct       `protobuf:"bytes,7,opt,name=event_data,json=eventData"`
	xxx_hidden_SandboxId          string                 `protobuf:"bytes,8,opt,name=sandbox_id,json=sandboxId"`
	xxx_hidden_SandboxBuildId     string                 `protobuf:"bytes,9,opt,name=sandbox_build_id,json=sandboxBuildId"`
	xxx_hidden_SandboxExecutionId string                 `protobuf:"bytes,10,opt,name=sandbox_execution_id,json=sandboxExecutionId"`
	xxx_hidden_SandboxTemplateId  string                 `protobuf:"bytes,11,opt,name=sandbox_template_id,json=sandboxTemplateId"`
	xxx_hidden_SandboxTeamId      string                 `protobuf:"bytes,12,opt,name=sandbox_team_id,json=sandboxTeamId"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SandboxEvent) Reset() {
	*x = SandboxEvent{}
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxEvent) ProtoMessage() {}

func (x *SandboxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SandboxEvent) GetEventId() string {
	if x != nil {
		return x.xxx_hidden_EventId
	}
	return ""
}

func (x *SandboxEvent) GetVersion() string {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return ""
}

func (x *SandboxEvent) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *SandboxEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *SandboxEvent) GetEventCategory() string {
	if x != nil {
		if x.xxx_hidden_EventCategory != nil {
			return *x.xxx_hidden_EventCategory
		}
		return ""
	}
	return ""
}

func (x *SandboxEvent) GetEventLabel() string {
	if x != nil {
		if x.xxx_hidden_EventLabel != nil {
			return *x.xxx_hidden_EventLabel
		}
		return ""
	}
	return ""
}

func (x *SandboxEvent) GetEventData() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_EventData
	}
	return nil
}

func (x *SandboxEvent) GetSandboxId() string {
	if x != nil {
		return x.xxx_hidden_SandboxId
	}
	return ""
}

func (x *SandboxEvent) GetSandboxBuildId() string {
	if x != nil {
		return x.xxx_hidden_SandboxBuildId
	}
	return ""
}

func (x *SandboxEvent) GetSandboxExecutionId() string {
	if x != nil {
		return x.xxx_hidden_SandboxExecutionId
	}
	return ""
}

func (x *SandboxEvent) GetSandboxTemplateId() string {
	if x != nil {
		return x.xxx_hidden_SandboxTemplateId
	}
	return ""
}

func (x *SandboxEvent) GetSandboxTeamId() string {
	if x != nil {
		return x.xxx_hidden_SandboxTeamId
	}
	return ""
}

func (x *SandboxEvent) SetEventId(v string) {
	x.xxx_hidden_EventId = v
}

func (x *SandboxEvent) SetVersion(v string) {
	x.xxx_hidden_Version = v
}

func (x *SandboxEvent) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *SandboxEvent) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *SandboxEvent) SetEventCategory(v string) {
	x.xxx_hidden_EventCategory = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *SandboxEvent) SetEventLabel(v string) {
	x.xxx_hidden_EventLabel = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *SandboxEvent) SetEventData(v *structpb.Struct) {
	x.xxx_hidden_EventData = v
}

func (x *SandboxEvent) SetSandboxId(v string) {
	x.xxx_hidden_SandboxId = v
}

func (x *SandboxEvent) SetSandboxBuildId(v string) {
	x.xxx_hidden_SandboxBuildId = v
}

func (x *SandboxEvent) SetSandboxExecutionId(v string) {
	x.xxx_hidden_SandboxExecutionId = v
}

func (x *SandboxEvent) SetSandboxTemplateId(v string) {
	x.xxx_hidden_SandboxTemplateId = v
}

func (x *SandboxEvent) SetSandboxTeamId(v string) {
	x.xxx_hidden_SandboxTeamId = v
}

func (x *SandboxEvent) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *SandboxEvent) HasEventCategory() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *SandboxEvent) HasEventLabel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *SandboxEvent) HasEventData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventData != nil
}

func (x *SandboxEvent) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *SandboxEvent) ClearEventCategory() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_EventCategory = nil
}

func (x *SandboxEvent) ClearEventLabel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_EventLabel = nil
}

func (x *SandboxEvent) ClearEventData() {
	x.xxx_hidden_EventData = nil
}

type SandboxEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventId   string
	Version   string
	Type      string
	Timestamp *timestamppb.Timestamp
	// Omitted when the source recorded no category. Superseded by the dotted
	// form of type; kept because the REST surface still publishes it.
	EventCategory *string
	// Omitted when the source recorded no label. Superseded by the dotted form
	// of type; kept because the REST surface still publishes it.
	EventLabel *string
	// Omitted when the source recorded no payload.
	EventData          *structpb.Struct
	SandboxId          string
	SandboxBuildId     string
	SandboxExecutionId string
	SandboxTemplateId  string
	SandboxTeamId      string
}

func (b0 SandboxEvent_builder) Build() *SandboxEvent {
	m0 := &SandboxEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventId = b.EventId
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Timestamp = b.Timestamp
	if b.EventCategory != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_EventCategory = b.EventCategory
	}
	if b.EventLabel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_EventLabel = b.EventLabel
	}
	x.xxx_hidden_EventData = b.EventData
	x.xxx_hidden_SandboxId = b.SandboxId
	x.xxx_hidden_SandboxBuildId = b.SandboxBuildId
	x.xxx_hidden_SandboxExecutionId = b.SandboxExecutionId
	x.xxx_hidden_SandboxTemplateId = b.SandboxTemplateId
	x.xxx_hidden_SandboxTeamId = b.SandboxTeamId
	return m0
}

type Pagination struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset      int32                  `protobuf:"varint,1,opt,name=offset"`
	xxx_hidden_Limit       int32                  `protobuf:"varint,2,opt,name=limit"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *Pagination) SetOffset(v int32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Pagination) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Pagination) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Pagination) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Pagination) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Offset = 0
}

func (x *Pagination) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

type Pagination_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Omission defaults to 0.
	Offset *int32
	// Omission defaults to 10.
	Limit *int32
}

func (b0 Pagination_builder) Build() *Pagination {
	m0 := &Pagination{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Limit = *b.Limit
	}
	return m0
}

type ListTeamSandboxEventsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamId      string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId"`
	xxx_hidden_ClusterId   *string                `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId"`
	xxx_hidden_EventTypes  []string               `protobuf:"bytes,3,rep,name=event_types,json=eventTypes"`
	xxx_hidden_Pagination  *Pagination            `protobuf:"bytes,4,opt,name=pagination"`
	xxx_hidden_OrderAsc    bool                   `protobuf:"varint,5,opt,name=order_asc,json=orderAsc"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListTeamSandboxEventsRequest) Reset() {
	*x = ListTeamSandboxEventsRequest{}
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamSandboxEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamSandboxEventsRequest) ProtoMessage() {}

func (x *ListTeamSandboxEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamSandboxEventsRequest) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *ListTeamSandboxEventsRequest) GetClusterId() string {
	if x != nil {
		if x.xxx_hidden_ClusterId != nil {
			return *x.xxx_hidden_ClusterId
		}
		return ""
	}
	return ""
}

func (x *ListTeamSandboxEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.xxx_hidden_EventTypes
	}
	return nil
}

func (x *ListTeamSandboxEventsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *ListTeamSandboxEventsRequest) GetOrderAsc() bool {
	if x != nil {
		return x.xxx_hidden_OrderAsc
	}
	return false
}

func (x *ListTeamSandboxEventsRequest) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *ListTeamSandboxEventsRequest) SetClusterId(v string) {
	x.xxx_hidden_ClusterId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *ListTeamSandboxEventsRequest) SetEventTypes(v []string) {
	x.xxx_hidden_EventTypes = v
}

func (x *ListTeamSandboxEventsRequest) SetPagination(v *Pagination) {
	x.xxx_hidden_Pagination = v
}

func (x *ListTeamSandboxEventsRequest) SetOrderAsc(v bool) {
	x.xxx_hidden_OrderAsc = v
}

func (x *ListTeamSandboxEventsRequest) HasClusterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListTeamSandboxEventsRequest) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *ListTeamSandboxEventsRequest) ClearClusterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClusterId = nil
}

func (x *ListTeamSandboxEventsRequest) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

type ListTeamSandboxEventsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamId string
	// Omission selects the local cluster.
	ClusterId *string
	// Empty returns every event type. The allowed event types are validated by
	// the server against the shared events package, the single source of truth
	// for sandbox event types.
	EventTypes []string
	// Omission selects the first page at the default size.
	Pagination *Pagination
	OrderAsc   bool
}

func (b0 ListTeamSandboxEventsRequest_builder) Build() *ListTeamSandboxEventsRequest {
	m0 := &ListTeamSandboxEventsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamId = b.TeamId
	if b.ClusterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_ClusterId = b.ClusterId
	}
	x.xxx_hidden_EventTypes = b.EventTypes
	x.xxx_hidden_Pagination = b.Pagination
	x.xxx_hidden_OrderAsc = b.OrderAsc
	return m0
}

type ListTeamSandboxEventsResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Events *[]*SandboxEvent       `protobuf:"bytes,1,rep,name=events"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListTeamSandboxEventsResponse) Reset() {
	*x = ListTeamSandboxEventsResponse{}
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamSandboxEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamSandboxEventsResponse) ProtoMessage() {}

func (x *ListTeamSandboxEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamSandboxEventsResponse) GetEvents() []*SandboxEvent {
	if x != nil {
		if x.xxx_hidden_Events != nil {
			return *x.xxx_hidden_Events
		}
	}
	return nil
}

func (x *ListTeamSandboxEventsResponse) SetEvents(v []*SandboxEvent) {
	x.xxx_hidden_Events = &v
}

type ListTeamSandboxEventsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Events []*SandboxEvent
}

func (b0 ListTeamSandboxEventsResponse_builder) Build() *ListTeamSandboxEventsResponse {
	m0 := &ListTeamSandboxEventsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Events = &b.Events
	return m0
}

type ListSandboxEventsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamId      string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId"`
	xxx_hidden_ClusterId   *string                `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId"`
	xxx_hidden_SandboxId   string                 `protobuf:"bytes,3,opt,name=sandbox_id,json=sandboxId"`
	xxx_hidden_EventTypes  []string               `protobuf:"bytes,4,rep,name=event_types,json=eventTypes"`
	xxx_hidden_Pagination  *Pagination            `protobuf:"bytes,5,opt,name=pagination"`
	xxx_hidden_OrderAsc    bool                   `protobuf:"varint,6,opt,name=order_asc,json=orderAsc"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListSandboxEventsRequest) Reset() {
	*x = ListSandboxEventsRequest{}
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxEventsRequest) ProtoMessage() {}

func (x *ListSandboxEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSandboxEventsRequest) GetTeamId() string {
	if x != nil {
		return x.xxx_hidden_TeamId
	}
	return ""
}

func (x *ListSandboxEventsRequest) GetClusterId() string {
	if x != nil {
		if x.xxx_hidden_ClusterId != nil {
			return *x.xxx_hidden_ClusterId
		}
		return ""
	}
	return ""
}

func (x *ListSandboxEventsRequest) GetSandboxId() string {
	if x != nil {
		return x.xxx_hidden_SandboxId
	}
	return ""
}

func (x *ListSandboxEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.xxx_hidden_EventTypes
	}
	return nil
}

func (x *ListSandboxEventsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *ListSandboxEventsRequest) GetOrderAsc() bool {
	if x != nil {
		return x.xxx_hidden_OrderAsc
	}
	return false
}

func (x *ListSandboxEventsRequest) SetTeamId(v string) {
	x.xxx_hidden_TeamId = v
}

func (x *ListSandboxEventsRequest) SetClusterId(v string) {
	x.xxx_hidden_ClusterId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *ListSandboxEventsRequest) SetSandboxId(v string) {
	x.xxx_hidden_SandboxId = v
}

func (x *ListSandboxEventsRequest) SetEventTypes(v []string) {
	x.xxx_hidden_EventTypes = v
}

func (x *ListSandboxEventsRequest) SetPagination(v *Pagination) {
	x.xxx_hidden_Pagination = v
}

func (x *ListSandboxEventsRequest) SetOrderAsc(v bool) {
	x.xxx_hidden_OrderAsc = v
}

func (x *ListSandboxEventsRequest) HasClusterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListSandboxEventsRequest) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *ListSandboxEventsRequest) ClearClusterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClusterId = nil
}

func (x *ListSandboxEventsRequest) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

type ListSandboxEventsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamId string
	// Omission selects the local cluster.
	ClusterId *string
	// The server trims a single dash-delimited suffix before reading, so both
	// the sandbox identifier and one execution of it select the same sandbox.
	SandboxId string
	// Empty returns every event type. The allowed event types are validated by
	// the server against the shared events package, the single source of truth
	// for sandbox event types.
	EventTypes []string
	// Omission selects the first page at the default size.
	Pagination *Pagination
	OrderAsc   bool
}

func (b0 ListSandboxEventsRequest_builder) Build() *ListSandboxEventsRequest {
	m0 := &ListSandboxEventsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamId = b.TeamId
	if b.ClusterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_ClusterId = b.ClusterId
	}
	x.xxx_hidden_SandboxId = b.SandboxId
	x.xxx_hidden_EventTypes = b.EventTypes
	x.xxx_hidden_Pagination = b.Pagination
	x.xxx_hidden_OrderAsc = b.OrderAsc
	return m0
}

type ListSandboxEventsResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Events *[]*SandboxEvent       `protobuf:"bytes,1,rep,name=events"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListSandboxEventsResponse) Reset() {
	*x = ListSandboxEventsResponse{}
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxEventsResponse) ProtoMessage() {}

func (x *ListSandboxEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSandboxEventsResponse) GetEvents() []*SandboxEvent {
	if x != nil {
		if x.xxx_hidden_Events != nil {
			return *x.xxx_hidden_Events
		}
	}
	return nil
}

func (x *ListSandboxEventsResponse) SetEvents(v []*SandboxEvent) {
	x.xxx_hidden_Events = &v
}

type ListSandboxEventsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Events []*SandboxEvent
}

func (b0 ListSandboxEventsResponse_builder) Build() *ListSandboxEventsResponse {
	m0 := &ListSandboxEventsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Events = &b.Events
	return m0
}

var File_e2b_webhooks_events_v1_sandbox_events_proto protoreflect.FileDescriptor

const file_e2b_webhooks_events_v1_sandbox_events_proto_rawDesc = "" +
	"\n" +
	"+e2b/webhooks/events/v1/sandbox_events.proto\x12\x16e2b.webhooks.events.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x04\n" +
	"\fSandboxEvent\x12#\n" +
	"\bevent_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aeventId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x0eevent_category\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x01R\reventCategory\x12&\n" +
	"\vevent_label\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x01R\n" +
	"eventLabel\x126\n" +
	"\n" +
	"event_data\x18\a \x01(\v2\x17.google.protobuf.StructR\teventData\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\b \x01(\tR\tsandboxId\x12(\n" +
	"\x10sandbox_build_id\x18\t \x01(\tR\x0esandboxBuildId\x120\n" +
	"\x14sandbox_execution_id\x18\n" +
	" \x01(\tR\x12sandboxExecutionId\x12.\n" +
	"\x13sandbox_template_id\x18\v \x01(\tR\x11sandboxTemplateId\x120\n" +
	"\x0fsandbox_team_id\x18\f \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rsandboxTeamId\"H\n" +
	"\n" +
	"Pagination\x12\x1d\n" +
	"\x06offset\x18\x01 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x06offset\x12\x1b\n" +
	"\x05limit\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05limit\"\xf1\x01\n" +
	"\x1cListTeamSandboxEventsRequest\x12!\n" +
	"\ateam_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x12,\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB\r\xbaH\x05r\x03\xb0\x01\x01\xaa\x01\x02\b\x01R\tclusterId\x12\x1f\n" +
	"\vevent_types\x18\x03 \x03(\tR\n" +
	"eventTypes\x12B\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\".e2b.webhooks.events.v1.PaginationR\n" +
	"pagination\x12\x1b\n" +
	"\torder_asc\x18\x05 \x01(\bR\borderAsc\"]\n" +
	"\x1dListTeamSandboxEventsResponse\x12<\n" +
	"\x06events\x18\x01 \x03(\v2$.e2b.webhooks.events.v1.SandboxEventR\x06events\"\x95\x02\n" +
	"\x18ListSandboxEventsRequest\x12!\n" +
	"\ateam_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06teamId\x12,\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB\r\xbaH\x05r\x03\xb0\x01\x01\xaa\x01\x02\b\x01R\tclusterId\x12&\n" +
	"\n" +
	"sandbox_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsandboxId\x12\x1f\n" +
	"\vevent_types\x18\x04 \x03(\tR\n" +
	"eventTypes\x12B\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\".e2b.webhooks.events.v1.PaginationR\n" +
	"pagination\x12\x1b\n" +
	"\torder_asc\x18\x06 \x01(\bR\borderAsc\"Y\n" +
	"\x19ListSandboxEventsResponse\x12<\n" +
	"\x06events\x18\x01 \x03(\v2$.e2b.webhooks.events.v1.SandboxEventR\x06events2\x97\x02\n" +
	"\x14SandboxEventsService\x12\x84\x01\n" +
	"\x15ListTeamSandboxEvents\x124.e2b.webhooks.events.v1.ListTeamSandboxEventsRequest\x1a5.e2b.webhooks.events.v1.ListTeamSandboxEventsResponse\x12x\n" +
	"\x11ListSandboxEvents\x120.e2b.webhooks.events.v1.ListSandboxEventsRequest\x1a1.e2b.webhooks.events.v1.ListSandboxEventsResponseB\x05\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_e2b_webhooks_events_v1_sandbox_events_proto_goTypes = []any{
	(*SandboxEvent)(nil),                  // 0: e2b.webhooks.events.v1.SandboxEvent
	(*Pagination)(nil),                    // 1: e2b.webhooks.events.v1.Pagination
	(*ListTeamSandboxEventsRequest)(nil),  // 2: e2b.webhooks.events.v1.ListTeamSandboxEventsRequest
	(*ListTeamSandboxEventsResponse)(nil), // 3: e2b.webhooks.events.v1.ListTeamSandboxEventsResponse
	(*ListSandboxEventsRequest)(nil),      // 4: e2b.webhooks.events.v1.ListSandboxEventsRequest
	(*ListSandboxEventsResponse)(nil),     // 5: e2b.webhooks.events.v1.ListSandboxEventsResponse
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),               // 7: google.protobuf.Struct
}
var file_e2b_webhooks_events_v1_sandbox_events_proto_depIdxs = []int32{
	6, // 0: e2b.webhooks.events.v1.SandboxEvent.timestamp:type_name -> google.protobuf.Timestamp
	7, // 1: e2b.webhooks.events.v1.SandboxEvent.event_data:type_name -> google.protobuf.Struct
	1, // 2: e2b.webhooks.events.v1.ListTeamSandboxEventsRequest.pagination:type_name -> e2b.webhooks.events.v1.Pagination
	0, // 3: e2b.webhooks.events.v1.ListTeamSandboxEventsResponse.events:type_name -> e2b.webhooks.events.v1.SandboxEvent
	1, // 4: e2b.webhooks.events.v1.ListSandboxEventsRequest.pagination:type_name -> e2b.webhooks.events.v1.Pagination
	0, // 5: e2b.webhooks.events.v1.ListSandboxEventsResponse.events:type_name -> e2b.webhooks.events.v1.SandboxEvent
	2, // 6: e2b.webhooks.events.v1.SandboxEventsService.ListTeamSandboxEvents:input_type -> e2b.webhooks.events.v1.ListTeamSandboxEventsRequest
	4, // 7: e2b.webhooks.events.v1.SandboxEventsService.ListSandboxEvents:input_type -> e2b.webhooks.events.v1.ListSandboxEventsRequest
	3, // 8: e2b.webhooks.events.v1.SandboxEventsService.ListTeamSandboxEvents:output_type -> e2b.webhooks.events.v1.ListTeamSandboxEventsResponse
	5, // 9: e2b.webhooks.events.v1.SandboxEventsService.ListSandboxEvents:output_type -> e2b.webhooks.events.v1.ListSandboxEventsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_e2b_webhooks_events_v1_sandbox_events_proto_init() }
func file_e2b_webhooks_events_v1_sandbox_events_proto_init() {
	if File_e2b_webhooks_events_v1_sandbox_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e2b_webhooks_events_v1_sandbox_events_proto_rawDesc), len(file_e2b_webhooks_events_v1_sandbox_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_e2b_webhooks_events_v1_sandbox_events_proto_goTypes,
		DependencyIndexes: file_e2b_webhooks_events_v1_sandbox_events_proto_depIdxs,
		MessageInfos:      file_e2b_webhooks_events_v1_sandbox_events_proto_msgTypes,
	}.Build()
	File_e2b_webhooks_events_v1_sandbox_events_proto = out.File
	file_e2b_webhooks_events_v1_sandbox_events_proto_goTypes = nil
	file_e2b_webhooks_events_v1_sandbox_events_proto_depIdxs = nil
}
