// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: e2b/webhooks/events/v1/sandbox_events.proto

package events

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxEventsService_ListTeamSandboxEvents_FullMethodName = "/e2b.webhooks.events.v1.SandboxEventsService/ListTeamSandboxEvents"
	SandboxEventsService_ListSandboxEvents_FullMethodName     = "/e2b.webhooks.events.v1.SandboxEventsService/ListSandboxEvents"
)

// SandboxEventsServiceClient is the client API for SandboxEventsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Reads the sandbox event history recorded for a team.
//
// The caller authenticates the user and supplies the resulting team and cluster
// identifiers. Reaching this service is the access-control boundary; any caller
// that can connect can read the events of any team it names.
//
// Reads are served from the named cluster: the local cluster is queried
// directly, any other through its edge. Events are eventually consistent with
// the sandbox activity that produced them.
type SandboxEventsServiceClient interface {
	ListTeamSandboxEvents(ctx context.Context, in *ListTeamSandboxEventsRequest, opts ...grpc.CallOption) (*ListTeamSandboxEventsResponse, error)
	ListSandboxEvents(ctx context.Context, in *ListSandboxEventsRequest, opts ...grpc.CallOption) (*ListSandboxEventsResponse, error)
}

type sandboxEventsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxEventsServiceClient(cc grpc.ClientConnInterface) SandboxEventsServiceClient {
	return &sandboxEventsServiceClient{cc}
}

func (c *sandboxEventsServiceClient) ListTeamSandboxEvents(ctx context.Context, in *ListTeamSandboxEventsRequest, opts ...grpc.CallOption) (*ListTeamSandboxEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeamSandboxEventsResponse)
	err := c.cc.Invoke(ctx, SandboxEventsService_ListTeamSandboxEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxEventsServiceClient) ListSandboxEvents(ctx context.Context, in *ListSandboxEventsRequest, opts ...grpc.CallOption) (*ListSandboxEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxEventsResponse)
	err := c.cc.Invoke(ctx, SandboxEventsService_ListSandboxEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxEventsServiceServer is the server API for SandboxEventsService service.
// All implementations must embed UnimplementedSandboxEventsServiceServer
// for forward compatibility.
//
// Reads the sandbox event history recorded for a team.
//
// The caller authenticates the user and supplies the resulting team and cluster
// identifiers. Reaching this service is the access-control boundary; any caller
// that can connect can read the events of any team it names.
//
// Reads are served from the named cluster: the local cluster is queried
// directly, any other through its edge. Events are eventually consistent with
// the sandbox activity that produced them.
type SandboxEventsServiceServer interface {
	ListTeamSandboxEvents(context.Context, *ListTeamSandboxEventsRequest) (*ListTeamSandboxEventsResponse, error)
	ListSandboxEvents(context.Context, *ListSandboxEventsRequest) (*ListSandboxEventsResponse, error)
	mustEmbedUnimplementedSandboxEventsServiceServer()
}

// UnimplementedSandboxEventsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxEventsServiceServer struct{}

func (UnimplementedSandboxEventsServiceServer) ListTeamSandboxEvents(context.Context, *ListTeamSandboxEventsRequest) (*ListTeamSandboxEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeamSandboxEvents not implemented")
}
func (UnimplementedSandboxEventsServiceServer) ListSandboxEvents(context.Context, *ListSandboxEventsRequest) (*ListSandboxEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxEvents not implemented")
}
func (UnimplementedSandboxEventsServiceServer) mustEmbedUnimplementedSandboxEventsServiceServer() {}
func (UnimplementedSandboxEventsServiceServer) testEmbeddedByValue()                              {}

// UnsafeSandboxEventsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxEventsServiceServer will
// result in compilation errors.
type UnsafeSandboxEventsServiceServer interface {
	mustEmbedUnimplementedSandboxEventsServiceServer()
}

func RegisterSandboxEventsServiceServer(s grpc.ServiceRegistrar, srv SandboxEventsServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxEventsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxEventsService_ServiceDesc, srv)
}

func _SandboxEventsService_ListTeamSandboxEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamSandboxEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxEventsServiceServer).ListTeamSandboxEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxEventsService_ListTeamSandboxEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxEventsServiceServer).ListTeamSandboxEvents(ctx, req.(*ListTeamSandboxEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxEventsService_ListSandboxEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxEventsServiceServer).ListSandboxEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxEventsService_ListSandboxEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxEventsServiceServer).ListSandboxEvents(ctx, req.(*ListSandboxEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxEventsService_ServiceDesc is the grpc.ServiceDesc for SandboxEventsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxEventsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "e2b.webhooks.events.v1.SandboxEventsService",
	HandlerType: (*SandboxEventsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTeamSandboxEvents",
			Handler:    _SandboxEventsService_ListTeamSandboxEvents_Handler,
		},
		{
			MethodName: "ListSandboxEvents",
			Handler:    _SandboxEventsService_ListSandboxEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "e2b/webhooks/events/v1/sandbox_events.proto",
}
