// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: register_team_cluster.sql

package dashboardqueries

import (
	"context"

	"github.com/google/uuid"
)

const assignTeamCluster = `-- name: AssignTeamCluster :one
WITH locked_team AS MATERIALIZED (
    SELECT cluster_id,
           POSITION('enterprise' IN LOWER(tier)) > 0 AS enterprise_eligible
    FROM public.teams
    WHERE id = $2::uuid
    FOR UPDATE
),
assigned AS (
    UPDATE public.teams AS team
    SET cluster_id = $1::uuid
    FROM locked_team
    WHERE team.id = $2::uuid
      AND (
          locked_team.cluster_id IS NOT DISTINCT FROM $1::uuid
          OR (
              locked_team.enterprise_eligible
              AND (
                  NOT $3::boolean
                  OR locked_team.cluster_id IS NULL
              )
          )
      )
    RETURNING TRUE
)
SELECT locked_team.cluster_id,
       EXISTS (
           SELECT
           FROM locked_team AS eligible_team
           WHERE eligible_team.enterprise_eligible
              OR eligible_team.cluster_id IS NOT DISTINCT FROM $1::uuid
       ) AS assignment_eligible,
       EXISTS (SELECT FROM assigned) AS assigned
FROM locked_team
`

type AssignTeamClusterParams struct {
	ClusterID        uuid.UUID
	TeamID           uuid.UUID
	PreserveExisting bool
}

type AssignTeamClusterRow struct {
	ClusterID          *uuid.UUID
	AssignmentEligible bool
	Assigned           bool
}

func (q *Queries) AssignTeamCluster(ctx context.Context, arg AssignTeamClusterParams) (AssignTeamClusterRow, error) {
	row := q.db.QueryRow(ctx, assignTeamCluster, arg.ClusterID, arg.TeamID, arg.PreserveExisting)
	var i AssignTeamClusterRow
	err := row.Scan(&i.ClusterID, &i.AssignmentEligible, &i.Assigned)
	return i, err
}

const clusterDeletionProtected = `-- name: ClusterDeletionProtected :one
SELECT EXISTS (
    SELECT FROM public.clusters
    WHERE id = $1::uuid
      AND deletion_protection
)
`

func (q *Queries) ClusterDeletionProtected(ctx context.Context, clusterID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, clusterDeletionProtected, clusterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const clusterUsedByMultipleTeams = `-- name: ClusterUsedByMultipleTeams :one
SELECT COUNT(DISTINCT team_id) > 1
FROM (
    SELECT id AS team_id FROM public.teams WHERE cluster_id = $1::uuid
    UNION
    SELECT team_id FROM public.active_envs WHERE cluster_id = $1::uuid
) AS cluster_teams
`

// True when more than one team is assigned to the cluster or owns live
// environments on it. One team's own environments do not count: deleting the
// cluster soft-deletes them.
func (q *Queries) ClusterUsedByMultipleTeams(ctx context.Context, clusterID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, clusterUsedByMultipleTeams, clusterID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createCluster = `-- name: CreateCluster :one
INSERT INTO public.clusters (
    id,
    name,
    endpoint,
    endpoint_tls,
    token,
    sandbox_proxy_domain,
    auth_org_id,
    deletion_protection
)
VALUES (
    COALESCE($1::uuid, gen_random_uuid()),
    $2::text,
    $3::text,
    $4::boolean,
    $5::text,
    $6::text,
    $7::text,
    $8::boolean
)
ON CONFLICT (id) DO UPDATE
SET id = EXCLUDED.id
WHERE clusters.name = EXCLUDED.name
  AND clusters.endpoint = EXCLUDED.endpoint
  AND clusters.endpoint_tls = EXCLUDED.endpoint_tls
  AND clusters.token = EXCLUDED.token
  AND clusters.sandbox_proxy_domain IS NOT DISTINCT FROM EXCLUDED.sandbox_proxy_domain
  AND clusters.auth_org_id IS NOT DISTINCT FROM EXCLUDED.auth_org_id
RETURNING id
`

type CreateClusterParams struct {
	ClusterID          *uuid.UUID
	Name               string
	Endpoint           string
	EndpointTls        bool
	Token              string
	SandboxProxyDomain *string
	AuthOrgID          *string
	DeletionProtection bool
}

// deletion_protection is set only on a new row. Registering an existing cluster
// again leaves its stored protection unchanged.
func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCluster,
		arg.ClusterID,
		arg.Name,
		arg.Endpoint,
		arg.EndpointTls,
		arg.Token,
		arg.SandboxProxyDomain,
		arg.AuthOrgID,
		arg.DeletionProtection,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCluster = `-- name: DeleteCluster :execrows
DELETE FROM public.clusters
WHERE id = $1::uuid
`

func (q *Queries) DeleteCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCluster, clusterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEnvironmentsActiveBuilds = `-- name: DeleteEnvironmentsActiveBuilds :exec
DELETE FROM public.active_template_builds
WHERE template_id = ANY($1::text[])
`

func (q *Queries) DeleteEnvironmentsActiveBuilds(ctx context.Context, envIds []string) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentsActiveBuilds, envIds)
	return err
}

const detachDeletedTemplatesFromCluster = `-- name: DetachDeletedTemplatesFromCluster :exec
UPDATE public.envs
SET cluster_id = NULL
WHERE cluster_id = $1::uuid
  AND deleted_at IS NOT NULL
`

func (q *Queries) DetachDeletedTemplatesFromCluster(ctx context.Context, clusterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, detachDeletedTemplatesFromCluster, clusterID)
	return err
}

const detachTeamCluster = `-- name: DetachTeamCluster :one
WITH locked_team AS MATERIALIZED (
    SELECT cluster_id
    FROM public.teams
    WHERE id = $1::uuid
    FOR UPDATE
),
detached AS (
    UPDATE public.teams AS team
    SET cluster_id = NULL
    FROM locked_team
    WHERE team.id = $1::uuid
      AND locked_team.cluster_id = $2::uuid
    RETURNING TRUE
)
SELECT locked_team.cluster_id,
       EXISTS (SELECT FROM detached) AS detached
FROM locked_team
`

type DetachTeamClusterParams struct {
	TeamID    uuid.UUID
	ClusterID uuid.UUID
}

type DetachTeamClusterRow struct {
	ClusterID *uuid.UUID
	Detached  bool
}

func (q *Queries) DetachTeamCluster(ctx context.Context, arg DetachTeamClusterParams) (DetachTeamClusterRow, error) {
	row := q.db.QueryRow(ctx, detachTeamCluster, arg.TeamID, arg.ClusterID)
	var i DetachTeamClusterRow
	err := row.Scan(&i.ClusterID, &i.Detached)
	return i, err
}

const releaseEnvironmentsAliases = `-- name: ReleaseEnvironmentsAliases :exec
DELETE FROM public.env_aliases
WHERE env_id = ANY($1::text[])
`

func (q *Queries) ReleaseEnvironmentsAliases(ctx context.Context, envIds []string) error {
	_, err := q.db.Exec(ctx, releaseEnvironmentsAliases, envIds)
	return err
}

const softDeleteClusterEnvironments = `-- name: SoftDeleteClusterEnvironments :many
UPDATE public.envs
SET deleted_at = NOW(), updated_at = NOW()
WHERE cluster_id = $1::uuid
  AND deleted_at IS NULL
RETURNING id
`

// Step 1 of cluster environment cleanup (run in a tx): soft-deletes every live
// template, snapshot template and paused sandbox snapshot on the cluster. The
// UPDATE waits on rows a concurrent build registration has locked, so the
// alias and active-build cleanup run as separate statements afterwards: their
// fresh snapshots see rows that registration committed during the wait.
func (q *Queries) SoftDeleteClusterEnvironments(ctx context.Context, clusterID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, softDeleteClusterEnvironments, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamClusterAssignment = `-- name: TeamClusterAssignment :one
SELECT cluster_id
FROM public.teams
WHERE id = $1::uuid
  AND cluster_id IS NOT NULL
`

func (q *Queries) TeamClusterAssignment(ctx context.Context, teamID uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, teamClusterAssignment, teamID)
	var cluster_id *uuid.UUID
	err := row.Scan(&cluster_id)
	return cluster_id, err
}
