// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_team.sql

package dashboardqueries

import (
	"context"

	"github.com/google/uuid"
)

const updateTeam = `-- name: UpdateTeam :one
UPDATE public.teams
SET
    name = CASE
        WHEN $1::bool THEN $2::text
        ELSE name
    END
WHERE id = $3::uuid
RETURNING id, name
`

type UpdateTeamParams struct {
	NameSet bool
	Name    *string
	TeamID  uuid.UUID
}

type UpdateTeamRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (UpdateTeamRow, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.NameSet, arg.Name, arg.TeamID)
	var i UpdateTeamRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
