// Predefined protovalidate rules shared by every contract, grouped into files
// named after the buf.validate rule message they extend. Extensions require
// edition 2023; consumers on any edition may import them. Field numbers use
// the 50000-99999 range reserved for private schemas.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: e2b/validate/v1/predefined_timestamp_rules.proto

package validate

import (
	validate "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_e2b_validate_v1_predefined_timestamp_rules_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*validate.TimestampRules)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "e2b.validate.v1.in_representable_range",
		Tag:           "varint,50000,opt,name=in_representable_range",
		Filename:      "e2b/validate/v1/predefined_timestamp_rules.proto",
	},
}

// Extension fields to validate.TimestampRules.
var (
	// Restricts a timestamp to the representable google.protobuf.Timestamp
	// range (0001-01-01 to 9999-12-31), the same check Timestamp.CheckValid
	// performs.
	//
	// optional bool in_representable_range = 50000;
	E_InRepresentableRange = &file_e2b_validate_v1_predefined_timestamp_rules_proto_extTypes[0]
)

var File_e2b_validate_v1_predefined_timestamp_rules_proto protoreflect.FileDescriptor

const file_e2b_validate_v1_predefined_timestamp_rules_proto_rawDesc = "" +
	"\n" +
	"0e2b/validate/v1/predefined_timestamp_rules.proto\x12\x0fe2b.validate.v1\x1a\x1bbuf/validate/validate.proto:\x88\x02\n" +
	"\x16in_representable_range\x12\x1c.buf.validate.TimestampRules\x18І\x03 \x01(\bB\xb1\x01\xc2H\xad\x01\n" +
	"\xaa\x01\n" +
	" timestamp.in_representable_range\x12\x19must be a valid timestamp\x1ak!rule || (this >= timestamp('0001-01-01T00:00:00Z') && this <= timestamp('9999-12-31T23:59:59.999999999Z'))R\x14inRepresentableRangeb\beditionsp\xe8\a"

var file_e2b_validate_v1_predefined_timestamp_rules_proto_goTypes = []any{
	(*validate.TimestampRules)(nil), // 0: buf.validate.TimestampRules
}
var file_e2b_validate_v1_predefined_timestamp_rules_proto_depIdxs = []int32{
	0, // 0: e2b.validate.v1.in_representable_range:extendee -> buf.validate.TimestampRules
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_e2b_validate_v1_predefined_timestamp_rules_proto_init() }
func file_e2b_validate_v1_predefined_timestamp_rules_proto_init() {
	if File_e2b_validate_v1_predefined_timestamp_rules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e2b_validate_v1_predefined_timestamp_rules_proto_rawDesc), len(file_e2b_validate_v1_predefined_timestamp_rules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_e2b_validate_v1_predefined_timestamp_rules_proto_goTypes,
		DependencyIndexes: file_e2b_validate_v1_predefined_timestamp_rules_proto_depIdxs,
		ExtensionInfos:    file_e2b_validate_v1_predefined_timestamp_rules_proto_extTypes,
	}.Build()
	File_e2b_validate_v1_predefined_timestamp_rules_proto = out.File
	file_e2b_validate_v1_predefined_timestamp_rules_proto_goTypes = nil
	file_e2b_validate_v1_predefined_timestamp_rules_proto_depIdxs = nil
}
