// Predefined protovalidate rules shared by every contract, grouped into files
// named after the buf.validate rule message they extend. Extensions require
// edition 2023; consumers on any edition may import them. Field numbers use
// the 50000-99999 range reserved for private schemas.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: e2b/validate/v1/predefined_string_rules.proto

package validate

import (
	validate "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_e2b_validate_v1_predefined_string_rules_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*validate.StringRules)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "e2b.validate.v1.http_url",
		Tag:           "varint,50000,opt,name=http_url",
		Filename:      "e2b/validate/v1/predefined_string_rules.proto",
	},
}

// Extension fields to validate.StringRules.
var (
	// An absolute http or https URL. The pattern requires a host, which
	// isUri() alone does not: RFC 3986 allows an empty authority.
	//
	// optional bool http_url = 50000;
	E_HttpUrl = &file_e2b_validate_v1_predefined_string_rules_proto_extTypes[0]
)

var File_e2b_validate_v1_predefined_string_rules_proto protoreflect.FileDescriptor

const file_e2b_validate_v1_predefined_string_rules_proto_rawDesc = "" +
	"\n" +
	"-e2b/validate/v1/predefined_string_rules.proto\x12\x0fe2b.validate.v1\x1a\x1bbuf/validate/validate.proto:\xae\x01\n" +
	"\bhttp_url\x12\x19.buf.validate.StringRules\x18І\x03 \x01(\bBv\xc2Hs\n" +
	"q\n" +
	"\x0fstring.http_url\x12!must be a valid http or https URL\x1a;!rule || (this.isUri() && this.matches('^https?://[^/?#]'))R\ahttpUrlb\beditionsp\xe8\a"

var file_e2b_validate_v1_predefined_string_rules_proto_goTypes = []any{
	(*validate.StringRules)(nil), // 0: buf.validate.StringRules
}
var file_e2b_validate_v1_predefined_string_rules_proto_depIdxs = []int32{
	0, // 0: e2b.validate.v1.http_url:extendee -> buf.validate.StringRules
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_e2b_validate_v1_predefined_string_rules_proto_init() }
func file_e2b_validate_v1_predefined_string_rules_proto_init() {
	if File_e2b_validate_v1_predefined_string_rules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e2b_validate_v1_predefined_string_rules_proto_rawDesc), len(file_e2b_validate_v1_predefined_string_rules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_e2b_validate_v1_predefined_string_rules_proto_goTypes,
		DependencyIndexes: file_e2b_validate_v1_predefined_string_rules_proto_depIdxs,
		ExtensionInfos:    file_e2b_validate_v1_predefined_string_rules_proto_extTypes,
	}.Build()
	File_e2b_validate_v1_predefined_string_rules_proto = out.File
	file_e2b_validate_v1_predefined_string_rules_proto_goTypes = nil
	file_e2b_validate_v1_predefined_string_rules_proto_depIdxs = nil
}
